/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef DEMOIPTABLE_H
#define DEMOIPTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(STEVE-TEST-MIB)
config_require(STEVE-TEST-MIB/demoIpTable/demoIpTable_interface)
config_require(STEVE-TEST-MIB/demoIpTable/demoIpTable_data_access)
config_require(STEVE-TEST-MIB/demoIpTable/demoIpTable_data_get)
config_require(STEVE-TEST-MIB/demoIpTable/demoIpTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for demoIpTable */
#include "demoIpTable_oids.h"

/* enum definions */
#include "demoIpTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_demoIpTable(void);
void shutdown_demoIpTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table demoIpTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * STEVE-TEST-MIB::demoIpTable is subid 1 of products.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.12345.1.1, length: 9
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review demoIpTable registration context.
     */
typedef netsnmp_data_list demoIpTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review demoIpTable data context structure.
 * This structure is used to represent the data for demoIpTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * demoIpTable.
 */
typedef struct demoIpTable_data_s {
    
        /*
         * demoIpInuse(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
         */
   long   demoIpInuse;
    
        /*
         * demoIpAddress(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h
         */
   char   demoIpAddress[65535];
size_t      demoIpAddress_len; /* # of char elements, not bytes */
    
        /*
         * demoMacAddress(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h
         */
   char   demoMacAddress[65535];
size_t      demoMacAddress_len; /* # of char elements, not bytes */
    
} demoIpTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review demoIpTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef demoIpTable_data demoIpTable_undo_data;

/*
 * TODO:120:r: |-> Review demoIpTable mib index.
 * This structure is used to represent the index for demoIpTable.
 */
typedef struct demoIpTable_mib_index_s {

        /*
         * demoIpIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
         */
   long   demoIpIndex;


} demoIpTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review demoIpTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_demoIpTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review demoIpTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * demoIpTable_rowreq_ctx pointer.
 */
typedef struct demoIpTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_demoIpTable_IDX_LEN];
    
    demoIpTable_mib_index        tbl_idx;
    
    demoIpTable_data              data;
    demoIpTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to demoIpTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *demoIpTable_data_list;

} demoIpTable_rowreq_ctx;

typedef struct demoIpTable_ref_rowreq_ctx_s {
    demoIpTable_rowreq_ctx *rowreq_ctx;
} demoIpTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int demoIpTable_pre_request(demoIpTable_registration * user_context);
    int demoIpTable_post_request(demoIpTable_registration * user_context,
        int rc);

    int demoIpTable_commit(demoIpTable_rowreq_ctx * rowreq_ctx);

    demoIpTable_rowreq_ctx *
                  demoIpTable_row_find_by_mib_index(demoIpTable_mib_index *mib_idx);

extern const oid demoIpTable_oid[];
extern const int demoIpTable_oid_size;


#include "demoIpTable_interface.h"
#include "demoIpTable_data_access.h"
#include "demoIpTable_data_get.h"
#include "demoIpTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DEMOIPTABLE_H */
/** @} */
