/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DEMOIPTABLE_OIDS_H
#define DEMOIPTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table demoIpTable */
#define DEMOIPTABLE_OID              1,3,6,1,4,1,12345,1,1


#define COLUMN_DEMOIPINDEX         1
    
#define COLUMN_DEMOIPINUSE         2
#define COLUMN_DEMOIPINUSE_FLAG    (0x1 << 0)
    
#define COLUMN_DEMOIPADDRESS         3
#define COLUMN_DEMOIPADDRESS_FLAG    (0x1 << 1)
    
#define COLUMN_DEMOMACADDRESS         4
#define COLUMN_DEMOMACADDRESS_FLAG    (0x1 << 2)
    

#define DEMOIPTABLE_MIN_COL   COLUMN_DEMOIPINUSE
#define DEMOIPTABLE_MAX_COL   COLUMN_DEMOMACADDRESS
    

    /*
     * TODO:405:r: Review DEMOIPTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define DEMOIPTABLE_SETTABLE_COLS (COLUMN_DEMOIPINUSE_FLAG | COLUMN_DEMOIPADDRESS_FLAG | COLUMN_DEMOMACADDRESS_FLAG)

#ifdef __cplusplus
}
#endif

#endif /* DEMOIPTABLE_OIDS_H */
