#!/bin/sh

if [ $# -le 2 -o $1 != "-m" ];then
    echo "GA -m \"information\" filelist"
    exit
fi

i=1
FILES=
for para in $@;do
    if [ $i -gt 2 ];then
        if [ ! -e ${para} ];then
            echo "${para} does not exist"
            exit
        fi
        FILES+=" ${para} "
    fi
    let i++
done

echo "will add ${FILES}"
git add -f ${FILES}

if [ $? -ne 0 ];then
    echo "git add failed"
    exit
fi

git commit -m $2

if [ $? -ne 0 ];then
    echo "git commit failed"
    exit
fi

git push


