#!/bin/sh

if [ $# -le 0 ];then
    echo "GA -m \"information\" filelist"
    exit 1
fi

if [ $# -eq 1 -a  "$1" = "-m" ];then
    echo "GA -m \"information\" filelist"
	exit 1
fi

i=1
FILES=
INF=

if [ "$1" = "-m" ];then
	INF=$2
fi

for para in "$@";do
    if [ ! -z "${INF}" -a $i -gt 2 ] || [ -z "${INF}" ];then
        if [ ! -e ${para} ];then
            echo "${para} does not exist"
            let i++
            continue
        fi
        FILES+=" ${para} "
    fi
    let i++
done

echo "will add ${FILES}"
git add -f ${FILES}

if [ $? -ne 0 ];then
    echo "git add failed"
    exit 1
fi

DATE=`date +%Y-%m-%d_%H%M%S`
if [ ! -z ${INF} ];then
	git commit -m "$2" ${FILES}
else
	git commit -m "GA update ${DATE}" ${FILES}
fi

if [ $? -ne 0 ];then
    echo "git commit failed"
    exit 1
fi

git push
exit 0


