#!/bin/sh

RESULT=`git diff . | grep "diff " | sed 's/diff --git a\///g' | sed 's/ b\/.*$//g'`

if [ -z "${RESULT}" ];then
	echo "no diff information"
	exit
fi

DATE=`date +%Y-%m-%d_%H%M%S`
echo "commit list:"
if [ $# -gt 0 ];then
	echo "$@"
	git commit -m "GC update ${DATE}" $@
else
	echo "${RESULT}"
	for i in `git diff | grep "diff " | sed 's/diff --git a\///g' | sed 's/ b\/.*$//g'`;do
    	git commit -m "GC update ${DATE}" $i
	done
fi

git push

