#!/bin/sh

RESULT=`git diff . | grep "diff " | sed 's/diff --git a\///g' | sed 's/ b\/.*$//g'`

if [ -z "${RESULT}" ];then
	echo "no diff information"
	exit
fi

echo "commit list:"
echo "${RESULT}"

DATE=`date +%Y-%m-%d_%H%M%S`

if [ $# -lt 0 ];then
	git commit -m "GC update ${DATE}" $@
else
	for i in `git diff | grep "diff " | sed 's/diff --git a\///g' | sed 's/ b\/.*$//g'`;do
    	git commit -m "GC update ${DATE}" $i
	done
fi

git push

