#!/bin/sh

if [ $# -le 2 -o $1 != "-m" ];then
    echo "GD -m \"informationi\ filelist"
    exit
fi

i=1
FILES=
for para in $@;do
    if [ $i -gt 2 ];then
        FILES+=" ${para} "
    fi
    let i++
done

echo "will delete ${FILES}"
git rm -f -r ${FILES}

if [ $? -ne 0 ];then
    echo "git rm failed"
    exit
fi

git commit -m $2

if [ $? -ne 0 ];then
    echo "git commit failed"
    exit
fi

git push


