/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11BssTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "dot11BssTable_interface.h"
#if 0
netsnmp_feature_require(baby_steps)
netsnmp_feature_require(row_merge)
netsnmp_feature_require(check_all_requests_error)

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11BssTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRCM-80211-MGMT-MIB::dot11BssTable is subid 14 of dot11MbssBase.
 * Its status is Deprecated.
 * OID: .1.3.6.1.4.1.4413.2.2.2.1.5.4.1.14, length: 15
*/
typedef struct dot11BssTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache;

   dot11BssTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} dot11BssTable_interface_ctx;

static dot11BssTable_interface_ctx dot11BssTable_if_ctx;

static void _dot11BssTable_container_init(
    dot11BssTable_interface_ctx *if_ctx);
static void _dot11BssTable_container_shutdown(
    dot11BssTable_interface_ctx *if_ctx);


netsnmp_container *
dot11BssTable_container_get( void )
{
    return dot11BssTable_if_ctx.container;
}

dot11BssTable_registration *
dot11BssTable_registration_get( void )
{
    return dot11BssTable_if_ctx.user_ctx;
}

dot11BssTable_registration *
dot11BssTable_registration_set( dot11BssTable_registration * newreg )
{
    dot11BssTable_registration * old = dot11BssTable_if_ctx.user_ctx;
    dot11BssTable_if_ctx.user_ctx = newreg;
    return old;
}

int
dot11BssTable_container_size( void )
{
    return CONTAINER_SIZE(dot11BssTable_if_ctx.container);
}

u_int
dot11BssTable_dirty_get( void )
{
    return dot11BssTable_if_ctx.table_dirty;
}

void
dot11BssTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("dot11BssTable:dot11BssTable_dirty_set",
                "called. was %d, now %d\n",
                dot11BssTable_if_ctx.table_dirty, status));
    dot11BssTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_dot11BssTable_pre_request;
static Netsnmp_Node_Handler _mfd_dot11BssTable_post_request;
static Netsnmp_Node_Handler _mfd_dot11BssTable_object_lookup;
static Netsnmp_Node_Handler _mfd_dot11BssTable_get_values;
static Netsnmp_Node_Handler _mfd_dot11BssTable_check_objects;
static Netsnmp_Node_Handler _mfd_dot11BssTable_undo_setup;
static Netsnmp_Node_Handler _mfd_dot11BssTable_set_values;
static Netsnmp_Node_Handler _mfd_dot11BssTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_dot11BssTable_undo_values;
static Netsnmp_Node_Handler _mfd_dot11BssTable_commit;
static Netsnmp_Node_Handler _mfd_dot11BssTable_undo_commit;
static Netsnmp_Node_Handler _mfd_dot11BssTable_irreversible_commit;

dot11BssTable_data *dot11BssTable_allocate_data(void);

/**
 * @internal
 * Initialize the table dot11BssTable 
 *    (Define its contents and how it's structured)
 */
void
_dot11BssTable_initialize_interface(dot11BssTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &dot11BssTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &dot11BssTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for dot11BssTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: ifIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = DOT11BSSTABLE_MIN_COL;
    tbl_info->max_column = DOT11BSSTABLE_MAX_COL;

    /*
     * save users context
     */
    dot11BssTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    dot11BssTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _dot11BssTable_container_init(&dot11BssTable_if_ctx);
    if (NULL == dot11BssTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for dot11BssTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_dot11BssTable_object_lookup;
    access_multiplexer->get_values = _mfd_dot11BssTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_dot11BssTable_pre_request;
    access_multiplexer->post_request = _mfd_dot11BssTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_dot11BssTable_check_objects;
    access_multiplexer->undo_setup = _mfd_dot11BssTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_dot11BssTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_dot11BssTable_set_values;
    access_multiplexer->undo_sets = _mfd_dot11BssTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_dot11BssTable_commit;
    access_multiplexer->undo_commit = _mfd_dot11BssTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_dot11BssTable_irreversible_commit;
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("dot11BssTable:init_dot11BssTable",
                "Registering dot11BssTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("dot11BssTable", handler,
                                                  dot11BssTable_oid,
                                                  dot11BssTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RWRITE
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table dot11BssTable\n");
        return;
    }
    reginfo->my_reg_void = &dot11BssTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            dot11BssTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != dot11BssTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(dot11BssTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _dot11BssTable_initialize_interface */

/**
 * @internal
 * Shutdown the table dot11BssTable
 */
void
_dot11BssTable_shutdown_interface(dot11BssTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _dot11BssTable_container_shutdown(&dot11BssTable_if_ctx);
}

void
dot11BssTable_valid_columns_set(netsnmp_column_info *vc)
{
    dot11BssTable_if_ctx.tbl_info.valid_columns = vc;
} /* dot11BssTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
dot11BssTable_index_to_oid(netsnmp_index *oid_idx,
                         dot11BssTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * ifIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
     */
    netsnmp_variable_list var_ifIndex;

    /*
     * set up varbinds
     */
    memset( &var_ifIndex, 0x00, sizeof(var_ifIndex) );
    var_ifIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_ifIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:dot11BssTable:dot11BssTable_index_to_oid","called\n"));

        /* ifIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H */
    snmp_set_var_value(&var_ifIndex, &mib_idx->ifIndex, sizeof(mib_idx->ifIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_ifIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_ifIndex );

    return err;
} /* dot11BssTable_index_to_oid */

/**
 * extract dot11BssTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
dot11BssTable_index_from_oid(netsnmp_index *oid_idx,
                         dot11BssTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * ifIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
     */
    netsnmp_variable_list var_ifIndex;

    /*
     * set up varbinds
     */
    memset( &var_ifIndex, 0x00, sizeof(var_ifIndex) );
    var_ifIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_ifIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:dot11BssTable:dot11BssTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_ifIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->ifIndex = *((long *)var_ifIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_ifIndex );

    return err;
} /* dot11BssTable_index_from_oid */


/*
 * dot11BssTable_allocate_data
 *
 * Purpose: create new dot11BssTable_data.
 */
dot11BssTable_data *
dot11BssTable_allocate_data(void)
{
    dot11BssTable_data *rtn = SNMP_MALLOC_TYPEDEF(dot11BssTable_data);

    DEBUGMSGTL(("verbose:dot11BssTable:dot11BssTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "dot11BssTable_data.\n");
    }

    return rtn;
} /* dot11BssTable_allocate_data */

/*
 * dot11BssTable_release_data
 *
 * Purpose: release dot11BssTable data.
 */
void
dot11BssTable_release_data(dot11BssTable_data *data)
{
    DEBUGMSGTL(("verbose:dot11BssTable:dot11BssTable_release_data","called\n"));

    free(data);
} /* dot11BssTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a dot11BssTable_rowreq_ctx
 */
dot11BssTable_rowreq_ctx *
dot11BssTable_allocate_rowreq_ctx(void)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(dot11BssTable_rowreq_ctx);

    DEBUGMSGTL(("internal:dot11BssTable:dot11BssTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "dot11BssTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->dot11BssTable_data_list = NULL;


    return rowreq_ctx;
} /* dot11BssTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a dot11BssTable_rowreq_ctx
 */
void
dot11BssTable_release_rowreq_ctx(dot11BssTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:dot11BssTable:dot11BssTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    

    if(rowreq_ctx->undo)
        dot11BssTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* dot11BssTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dot11BssTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:dot11BssTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = dot11BssTable_pre_request(dot11BssTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dot11BssTable","error %d from "
                    "dot11BssTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dot11BssTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        dot11BssTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:dot11BssTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && dot11BssTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "dot11BssTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = dot11BssTable_post_request(dot11BssTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dot11BssTable","error %d from "
                    "dot11BssTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_dot11BssTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * dot11BssTable_interface_ctx *if_ctx =
     *             (dot11BssTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        dot11BssTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_dot11BssTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dot11BssTable_get_column( dot11BssTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* dot11BssId(1)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/H */
    case COLUMN_DOT11BSSID:
    var->type = ASN_OCTET_STR;
rc = dot11BssId_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* dot11BssEnable(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSENABLE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = dot11BssEnable_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* dot11BssSsid(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/h */
    case COLUMN_DOT11BSSSSID:
    var->type = ASN_OCTET_STR;
rc = dot11BssSsid_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* dot11BssNetworkBridge(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSNETWORKBRIDGE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = dot11BssNetworkBridge_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* dot11BssSecurityMode(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSSECURITYMODE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = dot11BssSecurityMode_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* dot11BssClosedNetwork(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSCLOSEDNETWORK:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = dot11BssClosedNetwork_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* dot11BssAccessMode(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSACCESSMODE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = dot11BssAccessMode_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (DOT11BSSTABLE_MIN_COL <= column && column <= DOT11BSSTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _dot11BssTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _dot11BssTable_get_column */

int
_mfd_dot11BssTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _dot11BssTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_dot11BssTable_check_column( dot11BssTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* dot11BssId(1)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/H */
    case COLUMN_DOT11BSSID:
    rc = netsnmp_check_vb_type_and_max_size( var, ASN_OCTET_STR,
        sizeof( rowreq_ctx->data.dot11BssId ) );
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssId",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssId_check_value( rowreq_ctx, (char *)var->val.string, var->val_len );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssId_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssEnable(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSENABLE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.dot11BssEnable ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != TRUTHVALUE_TRUE )
 && ( *var->val.integer != TRUTHVALUE_FALSE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssEnable",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssEnable_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssEnable_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssSsid(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/h */
    case COLUMN_DOT11BSSSSID:
    rc = netsnmp_check_vb_type_and_max_size( var, ASN_OCTET_STR,
        sizeof( rowreq_ctx->data.dot11BssSsid ) );
    /* check defined range(s). */
    if( (SNMPERR_SUCCESS == rc)
       && ((var->val_len < 0) || (var->val_len > 32))
     ) {
        rc = SNMP_ERR_WRONGLENGTH;
    }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssSsid",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssSsid_check_value( rowreq_ctx, (char *)var->val.string, var->val_len );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssSsid_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssNetworkBridge(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSNETWORKBRIDGE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.dot11BssNetworkBridge ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != DOT11BSSNETWORKBRIDGE_LAN )
 && ( *var->val.integer != DOT11BSSNETWORKBRIDGE_GUEST )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssNetworkBridge",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssNetworkBridge_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssNetworkBridge_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssSecurityMode(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSSECURITYMODE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.dot11BssSecurityMode ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != DOT11BSSSECURITYMODE_DISABLED )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WEP )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPAPSK )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPA2PSK )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPAENTERPRISE )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPA2ENTERPRISE )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_RADIUSWEP )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPAWPA2PSK )
 && ( *var->val.integer != DOT11BSSSECURITYMODE_WPAWPA2ENTERPRISE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssSecurityMode",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssSecurityMode_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssSecurityMode_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssClosedNetwork(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSCLOSEDNETWORK:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.dot11BssClosedNetwork ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != TRUTHVALUE_TRUE )
 && ( *var->val.integer != TRUTHVALUE_FALSE )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssClosedNetwork",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssClosedNetwork_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssClosedNetwork_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* dot11BssAccessMode(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSACCESSMODE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.dot11BssAccessMode ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
 && ( *var->val.integer != DOT11BSSACCESSMODE_ALLOWANY )
 && ( *var->val.integer != DOT11BSSACCESSMODE_ALLOWLIST )
 && ( *var->val.integer != DOT11BSSACCESSMODE_DENYLIST )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:_dot11BssTable_check_column:dot11BssAccessMode",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = dot11BssAccessMode_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from dot11BssAccessMode_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _dot11BssTable_check_column\n", column);
    }

    return rc;
} /* _dot11BssTable_check_column */

int
_mfd_dot11BssTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _dot11BssTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dot11BssTable_undo_setup_column( dot11BssTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* dot11BssId(1)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/H */
    case COLUMN_DOT11BSSID:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSID_FLAG;
        rc = dot11BssId_undo_setup(rowreq_ctx );
        break;

    /* dot11BssEnable(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSENABLE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSENABLE_FLAG;
        rc = dot11BssEnable_undo_setup(rowreq_ctx );
        break;

    /* dot11BssSsid(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/h */
    case COLUMN_DOT11BSSSSID:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSSSID_FLAG;
        rc = dot11BssSsid_undo_setup(rowreq_ctx );
        break;

    /* dot11BssNetworkBridge(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSNETWORKBRIDGE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSNETWORKBRIDGE_FLAG;
        rc = dot11BssNetworkBridge_undo_setup(rowreq_ctx );
        break;

    /* dot11BssSecurityMode(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSSECURITYMODE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSSECURITYMODE_FLAG;
        rc = dot11BssSecurityMode_undo_setup(rowreq_ctx );
        break;

    /* dot11BssClosedNetwork(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSCLOSEDNETWORK:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSCLOSEDNETWORK_FLAG;
        rc = dot11BssClosedNetwork_undo_setup(rowreq_ctx );
        break;

    /* dot11BssAccessMode(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSACCESSMODE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSACCESSMODE_FLAG;
        rc = dot11BssAccessMode_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _dot11BssTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _dot11BssTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_dot11BssTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = dot11BssTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = dot11BssTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                    "dot11BssTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _dot11BssTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                            "dot11BssTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_dot11BssTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = dot11BssTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                    "dot11BssTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         dot11BssTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_undo_cleanup */
#endif
/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
int
_dot11BssTable_set_column( dot11BssTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* dot11BssId(1)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/H */
    case COLUMN_DOT11BSSID:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSID_FLAG;
        rc = dot11BssId_set(rowreq_ctx, (char *)var->val.string, var->val_len );
        break;

    /* dot11BssEnable(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSENABLE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSENABLE_FLAG;
        rc = dot11BssEnable_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* dot11BssSsid(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/h */
    case COLUMN_DOT11BSSSSID:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSSSID_FLAG;
        rc = dot11BssSsid_set(rowreq_ctx, (char *)var->val.string, var->val_len );
        break;

    /* dot11BssNetworkBridge(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSNETWORKBRIDGE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSNETWORKBRIDGE_FLAG;
        rc = dot11BssNetworkBridge_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* dot11BssSecurityMode(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSSECURITYMODE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSSECURITYMODE_FLAG;
        rc = dot11BssSecurityMode_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* dot11BssClosedNetwork(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSCLOSEDNETWORK:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSCLOSEDNETWORK_FLAG;
        rc = dot11BssClosedNetwork_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* dot11BssAccessMode(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSACCESSMODE:
        rowreq_ctx->column_set_flags |= COLUMN_DOT11BSSACCESSMODE_FLAG;
        rc = dot11BssAccessMode_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _dot11BssTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _dot11BssTable_set_column */
#if 0
int
_mfd_dot11BssTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _dot11BssTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                        "dot11BssTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_dot11BssTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = dot11BssTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                    "dot11BssTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        dot11BssTable_dirty_set( dot11BssTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_dot11BssTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = dot11BssTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            dot11BssTable_dirty_set( d - 1 );
    }

    rc = dot11BssTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                    "dot11BssTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "dot11BssTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_dot11BssTable_undo_column( dot11BssTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* dot11BssId(1)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/H */
    case COLUMN_DOT11BSSID:
        rc = dot11BssId_undo(rowreq_ctx);
        break;

    /* dot11BssEnable(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSENABLE:
        rc = dot11BssEnable_undo(rowreq_ctx);
        break;

    /* dot11BssSsid(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/h */
    case COLUMN_DOT11BSSSSID:
        rc = dot11BssSsid_undo(rowreq_ctx);
        break;

    /* dot11BssNetworkBridge(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSNETWORKBRIDGE:
        rc = dot11BssNetworkBridge_undo(rowreq_ctx);
        break;

    /* dot11BssSecurityMode(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSSECURITYMODE:
        rc = dot11BssSecurityMode_undo(rowreq_ctx);
        break;

    /* dot11BssClosedNetwork(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSCLOSEDNETWORK:
        rc = dot11BssClosedNetwork_undo(rowreq_ctx);
        break;

    /* dot11BssAccessMode(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_DOT11BSSACCESSMODE:
        rc = dot11BssAccessMode_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _dot11BssTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _dot11BssTable_undo_column */

int
_mfd_dot11BssTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = dot11BssTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                    "dot11BssTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _dot11BssTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("dot11BssTable:mfd","error %d from "
                        "dot11BssTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_dot11BssTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    dot11BssTable_rowreq_ctx *rowreq_ctx = (dot11BssTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:dot11BssTable:_mfd_dot11BssTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(dot11BssTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_dot11BssTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free(netsnmp_container *container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:dot11BssTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for dot11BssTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return dot11BssTable_container_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:dot11BssTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in dot11BssTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    _container_free(container);
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(dot11BssTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:dot11BssTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    dot11BssTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:dot11BssTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in dot11BssTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    dot11BssTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_dot11BssTable_container_init(dot11BssTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_container_init","called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         dot11BssTable_oid,
                                         dot11BssTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for dot11BssTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    dot11BssTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("dot11BssTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "dot11BssTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void*)if_ctx->container;
} /* _dot11BssTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_dot11BssTable_container_shutdown(dot11BssTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:dot11BssTable:_dot11BssTable_container_shutdown","called\n"));

    dot11BssTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _dot11BssTable_container_shutdown */


dot11BssTable_rowreq_ctx *
dot11BssTable_row_find_by_mib_index(dot11BssTable_mib_index *mib_idx)
{
    dot11BssTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = dot11BssTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (dot11BssTable_rowreq_ctx*)CONTAINER_FIND(dot11BssTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}
#endif

