/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "clabWIFIAccessPointTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clabWIFIAccessPointTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CLAB-WIFI-MIB::clabWIFIAccessPointTable is subid 6 of clabWIFIObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6, length: 12
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     * +-------------+        +==============+
     * |    row    |f|<-------||  object    ||
     * |  create   |1|      E ||  lookup    ||
     * +-------------+        +==============+
     *     E |   | S                 | S
     *       |   +------------------>|
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                               |
     *                          (err && f1)------------------->+
     *                               |                         |
     *                        +--------------+         +--------------+
     *                        |    post      |<--------|      row     |
     *                        |   request    |       U |    release   |
     *                        +--------------+         +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * clabWIFIAccessPointTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * clabWIFIAccessPointTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIAccessPointTable_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup clabWIFIAccessPointTable undo.
     * set up clabWIFIAccessPointTable undo information, in preparation for a set.
     * Undo storage is in (* clabWIFIAccessPointRowStatus_val_ptr )*
     */

    return rc;
} /* clabWIFIAccessPointTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIAccessPointTable_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> clabWIFIAccessPointTable undo.
     * clabWIFIAccessPointTable undo information, in response to a failed set.
     * Undo storage is in (* clabWIFIAccessPointRowStatus_val_ptr )*
     */

    return rc;
} /* clabWIFIAccessPointTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAccessPointTable_undo_cleanup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup clabWIFIAccessPointTable undo.
     * Undo storage is in (* clabWIFIAccessPointRowStatus_val_ptr )*
     */

    return rc;
} /* clabWIFIAccessPointTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIAccessPointTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIAccessPointTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAccessPointTable_commit( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit clabWIFIAccessPointTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_CLABWIFIACCESSPOINTENABLE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTENABLE_FLAG; /* clear clabWIFIAccessPointEnable */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointEnable.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointEnable commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointEnable
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTENABLE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTSTATUS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTSTATUS_FLAG; /* clear clabWIFIAccessPointStatus */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointStatus.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointStatus commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointStatus
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTSTATUS_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTALIAS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTALIAS_FLAG; /* clear clabWIFIAccessPointAlias */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointAlias.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointAlias commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointAlias
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTALIAS_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTSSIDREFERENCE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTSSIDREFERENCE_FLAG; /* clear clabWIFIAccessPointSSIDReference */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointSSIDReference.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointSSIDReference commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointSSIDReference
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTSSIDREFERENCE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTSSIDADVERTISEMENTENABLED_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTSSIDADVERTISEMENTENABLED_FLAG; /* clear clabWIFIAccessPointSSIDAdvertisementEnabled */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointSSIDAdvertisementEnabled.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointSSIDAdvertisementEnabled commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointSSIDAdvertisementEnabled
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTSSIDADVERTISEMENTENABLED_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTRETRYLIMIT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTRETRYLIMIT_FLAG; /* clear clabWIFIAccessPointRetryLimit */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointRetryLimit.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointRetryLimit commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointRetryLimit
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTRETRYLIMIT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTWMMCAPABILITY_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTWMMCAPABILITY_FLAG; /* clear clabWIFIAccessPointWMMCapability */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointWMMCapability.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointWMMCapability commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointWMMCapability
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTWMMCAPABILITY_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTUAPSDCAPABILITY_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTUAPSDCAPABILITY_FLAG; /* clear clabWIFIAccessPointUAPSDCapability */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointUAPSDCapability.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointUAPSDCapability commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointUAPSDCapability
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTUAPSDCAPABILITY_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTWMMENABLE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTWMMENABLE_FLAG; /* clear clabWIFIAccessPointWMMEnable */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointWMMEnable.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointWMMEnable commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointWMMEnable
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTWMMENABLE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTUAPSDENABLE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTUAPSDENABLE_FLAG; /* clear clabWIFIAccessPointUAPSDEnable */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointUAPSDEnable.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointUAPSDEnable commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointUAPSDEnable
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTUAPSDENABLE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTASSOCIATEDDEVICENUMBEROFENTRIES_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTASSOCIATEDDEVICENUMBEROFENTRIES_FLAG; /* clear clabWIFIAccessPointAssociatedDeviceNumberOfEntries */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointAssociatedDeviceNumberOfEntries.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointAssociatedDeviceNumberOfEntries commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointAssociatedDeviceNumberOfEntries
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTASSOCIATEDDEVICENUMBEROFENTRIES_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIACCESSPOINTROWSTATUS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIACCESSPOINTROWSTATUS_FLAG; /* clear clabWIFIAccessPointRowStatus */
       /*
        * TODO:482:o: |-> commit column clabWIFIAccessPointRowStatus.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAccessPointTable column clabWIFIAccessPointRowStatus commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAccessPointRowStatus
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIACCESSPOINTROWSTATUS_FLAG;
       }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* clabWIFIAccessPointTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIAccessPointTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIAccessPointTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAccessPointTable_undo_commit( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo clabWIFIAccessPointTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* clabWIFIAccessPointTable_undo_commit */

/*
 * TODO:440:M: Implement clabWIFIAccessPointTable node value checks.
 * TODO:450:M: Implement clabWIFIAccessPointTable undo functions.
 * TODO:460:M: Implement clabWIFIAccessPointTable set functions.
 * TODO:480:M: Implement clabWIFIAccessPointTable commit functions.
 */
/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointEnable
 * clabWIFIAccessPointEnable is subid 2 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.2
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.Enable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointEnable_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointEnable_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointEnable_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointEnable_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointEnable value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointEnable value not illegal */
} /* clabWIFIAccessPointEnable_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointEnable_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointEnable_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointEnable undo.
     */
    /*
     * copy clabWIFIAccessPointEnable data
     * set rowreq_ctx->undo->clabWIFIAccessPointEnable from rowreq_ctx->data.clabWIFIAccessPointEnable
     */
    rowreq_ctx->undo->clabWIFIAccessPointEnable = rowreq_ctx->data.clabWIFIAccessPointEnable;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointEnable_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointEnable_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointEnable_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointEnable_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointEnable_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointEnable value.
     * set clabWIFIAccessPointEnable value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointEnable = clabWIFIAccessPointEnable_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointEnable_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointEnable_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointEnable_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointEnable undo.
     */
    /*
     * copy clabWIFIAccessPointEnable data
     * set rowreq_ctx->data.clabWIFIAccessPointEnable from rowreq_ctx->undo->clabWIFIAccessPointEnable
     */
    rowreq_ctx->data.clabWIFIAccessPointEnable = rowreq_ctx->undo->clabWIFIAccessPointEnable;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointEnable_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointStatus
 * clabWIFIAccessPointStatus is subid 3 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.3
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.Status.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 4/8. Values:  disabled(1), enabled(2), errorMisconfigured(3), error(4)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointStatus_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  disabled(1), enabled(2), errorMisconfigured(3), error(4)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointStatus_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointStatus_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointStatus_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointStatus value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointStatus value not illegal */
} /* clabWIFIAccessPointStatus_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointStatus_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointStatus_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointStatus undo.
     */
    /*
     * copy clabWIFIAccessPointStatus data
     * set rowreq_ctx->undo->clabWIFIAccessPointStatus from rowreq_ctx->data.clabWIFIAccessPointStatus
     */
    rowreq_ctx->undo->clabWIFIAccessPointStatus = rowreq_ctx->data.clabWIFIAccessPointStatus;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointStatus_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointStatus_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointStatus_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointStatus_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointStatus_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointStatus value.
     * set clabWIFIAccessPointStatus value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointStatus = clabWIFIAccessPointStatus_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointStatus_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointStatus_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointStatus_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointStatus undo.
     */
    /*
     * copy clabWIFIAccessPointStatus data
     * set rowreq_ctx->data.clabWIFIAccessPointStatus from rowreq_ctx->undo->clabWIFIAccessPointStatus
     */
    rowreq_ctx->data.clabWIFIAccessPointStatus = rowreq_ctx->undo->clabWIFIAccessPointStatus;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointStatus_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointAlias
 * clabWIFIAccessPointAlias is subid 4 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.4
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.Alias.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255t
 *
 * Ranges:  0 - 64;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointAlias_val_ptr
 *        A char containing the new value.
 * @param clabWIFIAccessPointAlias_val_ptr_len
 *        The size (in bytes) of the data pointed to by clabWIFIAccessPointAlias_val_ptr
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_OCTET_STR
 *    The length is < sizeof(rowreq_ctx->data.clabWIFIAccessPointAlias).
 *    The length is in (one of) the range set(s):  0 - 64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointAlias_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, char *clabWIFIAccessPointAlias_val_ptr,  size_t clabWIFIAccessPointAlias_val_ptr_len)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAlias_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != clabWIFIAccessPointAlias_val_ptr);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointAlias value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointAlias value not illegal */
} /* clabWIFIAccessPointAlias_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointAlias_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAlias_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointAlias undo.
     */
    /*
     * copy clabWIFIAccessPointAlias and clabWIFIAccessPointAlias_len data
     * set rowreq_ctx->undo->clabWIFIAccessPointAlias from rowreq_ctx->data.clabWIFIAccessPointAlias
     */
    memcpy( rowreq_ctx->undo->clabWIFIAccessPointAlias, rowreq_ctx->data.clabWIFIAccessPointAlias,
            (rowreq_ctx->data.clabWIFIAccessPointAlias_len * sizeof(rowreq_ctx->undo->clabWIFIAccessPointAlias[0])));
    rowreq_ctx->undo->clabWIFIAccessPointAlias_len = rowreq_ctx->data.clabWIFIAccessPointAlias_len;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointAlias_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointAlias_val_ptr
 *        A char containing the new value.
 * @param clabWIFIAccessPointAlias_val_ptr_len
 *        The size (in bytes) of the data pointed to by clabWIFIAccessPointAlias_val_ptr
 */
int
clabWIFIAccessPointAlias_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, char *clabWIFIAccessPointAlias_val_ptr,  size_t clabWIFIAccessPointAlias_val_ptr_len )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAlias_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != clabWIFIAccessPointAlias_val_ptr);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointAlias value.
     * set clabWIFIAccessPointAlias value in rowreq_ctx->data
     */
    memcpy( rowreq_ctx->data.clabWIFIAccessPointAlias, clabWIFIAccessPointAlias_val_ptr, clabWIFIAccessPointAlias_val_ptr_len );
    /** convert bytes to number of char */
    rowreq_ctx->data.clabWIFIAccessPointAlias_len = clabWIFIAccessPointAlias_val_ptr_len / sizeof(clabWIFIAccessPointAlias_val_ptr[0]);

    return MFD_SUCCESS;
} /* clabWIFIAccessPointAlias_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointAlias_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAlias_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointAlias undo.
     */
    /*
     * copy clabWIFIAccessPointAlias and clabWIFIAccessPointAlias_len data
     * set rowreq_ctx->data.clabWIFIAccessPointAlias from rowreq_ctx->undo->clabWIFIAccessPointAlias
     */
    memcpy( rowreq_ctx->data.clabWIFIAccessPointAlias, rowreq_ctx->undo->clabWIFIAccessPointAlias,
            (rowreq_ctx->undo->clabWIFIAccessPointAlias_len * sizeof(rowreq_ctx->data.clabWIFIAccessPointAlias[0])));
    rowreq_ctx->data.clabWIFIAccessPointAlias_len = rowreq_ctx->undo->clabWIFIAccessPointAlias_len;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointAlias_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointSSIDReference
 * clabWIFIAccessPointSSIDReference is subid 5 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.5
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.Reference.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointSSIDReference_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointSSIDReference_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointSSIDReference_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDReference_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointSSIDReference value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointSSIDReference value not illegal */
} /* clabWIFIAccessPointSSIDReference_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointSSIDReference_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDReference_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointSSIDReference undo.
     */
    /*
     * copy clabWIFIAccessPointSSIDReference data
     * set rowreq_ctx->undo->clabWIFIAccessPointSSIDReference from rowreq_ctx->data.clabWIFIAccessPointSSIDReference
     */
    rowreq_ctx->undo->clabWIFIAccessPointSSIDReference = rowreq_ctx->data.clabWIFIAccessPointSSIDReference;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDReference_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointSSIDReference_val
 *        A u_long containing the new value.
 */
int
clabWIFIAccessPointSSIDReference_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointSSIDReference_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDReference_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointSSIDReference value.
     * set clabWIFIAccessPointSSIDReference value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointSSIDReference = clabWIFIAccessPointSSIDReference_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDReference_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointSSIDReference_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDReference_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointSSIDReference undo.
     */
    /*
     * copy clabWIFIAccessPointSSIDReference data
     * set rowreq_ctx->data.clabWIFIAccessPointSSIDReference from rowreq_ctx->undo->clabWIFIAccessPointSSIDReference
     */
    rowreq_ctx->data.clabWIFIAccessPointSSIDReference = rowreq_ctx->undo->clabWIFIAccessPointSSIDReference;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDReference_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointSSIDAdvertisementEnabled
 * clabWIFIAccessPointSSIDAdvertisementEnabled is subid 6 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.6
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.AdvertisementEnabled.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointSSIDAdvertisementEnabled_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointSSIDAdvertisementEnabled_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointSSIDAdvertisementEnabled_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDAdvertisementEnabled_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointSSIDAdvertisementEnabled value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointSSIDAdvertisementEnabled value not illegal */
} /* clabWIFIAccessPointSSIDAdvertisementEnabled_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointSSIDAdvertisementEnabled_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDAdvertisementEnabled_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointSSIDAdvertisementEnabled undo.
     */
    /*
     * copy clabWIFIAccessPointSSIDAdvertisementEnabled data
     * set rowreq_ctx->undo->clabWIFIAccessPointSSIDAdvertisementEnabled from rowreq_ctx->data.clabWIFIAccessPointSSIDAdvertisementEnabled
     */
    rowreq_ctx->undo->clabWIFIAccessPointSSIDAdvertisementEnabled = rowreq_ctx->data.clabWIFIAccessPointSSIDAdvertisementEnabled;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDAdvertisementEnabled_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointSSIDAdvertisementEnabled_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointSSIDAdvertisementEnabled_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointSSIDAdvertisementEnabled_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDAdvertisementEnabled_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointSSIDAdvertisementEnabled value.
     * set clabWIFIAccessPointSSIDAdvertisementEnabled value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointSSIDAdvertisementEnabled = clabWIFIAccessPointSSIDAdvertisementEnabled_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDAdvertisementEnabled_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointSSIDAdvertisementEnabled_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointSSIDAdvertisementEnabled_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointSSIDAdvertisementEnabled undo.
     */
    /*
     * copy clabWIFIAccessPointSSIDAdvertisementEnabled data
     * set rowreq_ctx->data.clabWIFIAccessPointSSIDAdvertisementEnabled from rowreq_ctx->undo->clabWIFIAccessPointSSIDAdvertisementEnabled
     */
    rowreq_ctx->data.clabWIFIAccessPointSSIDAdvertisementEnabled = rowreq_ctx->undo->clabWIFIAccessPointSSIDAdvertisementEnabled;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointSSIDAdvertisementEnabled_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointRetryLimit
 * clabWIFIAccessPointRetryLimit is subid 7 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.7
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.RetryLimit.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 7;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointRetryLimit_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  0 - 7
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointRetryLimit_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointRetryLimit_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRetryLimit_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointRetryLimit value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointRetryLimit value not illegal */
} /* clabWIFIAccessPointRetryLimit_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointRetryLimit_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRetryLimit_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointRetryLimit undo.
     */
    /*
     * copy clabWIFIAccessPointRetryLimit data
     * set rowreq_ctx->undo->clabWIFIAccessPointRetryLimit from rowreq_ctx->data.clabWIFIAccessPointRetryLimit
     */
    rowreq_ctx->undo->clabWIFIAccessPointRetryLimit = rowreq_ctx->data.clabWIFIAccessPointRetryLimit;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointRetryLimit_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointRetryLimit_val
 *        A u_long containing the new value.
 */
int
clabWIFIAccessPointRetryLimit_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointRetryLimit_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRetryLimit_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointRetryLimit value.
     * set clabWIFIAccessPointRetryLimit value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointRetryLimit = clabWIFIAccessPointRetryLimit_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointRetryLimit_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointRetryLimit_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRetryLimit_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointRetryLimit undo.
     */
    /*
     * copy clabWIFIAccessPointRetryLimit data
     * set rowreq_ctx->data.clabWIFIAccessPointRetryLimit from rowreq_ctx->undo->clabWIFIAccessPointRetryLimit
     */
    rowreq_ctx->data.clabWIFIAccessPointRetryLimit = rowreq_ctx->undo->clabWIFIAccessPointRetryLimit;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointRetryLimit_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointWMMCapability
 * clabWIFIAccessPointWMMCapability is subid 8 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.8
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.WMMCapability.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointWMMCapability_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointWMMCapability_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointWMMCapability_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMCapability_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointWMMCapability value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointWMMCapability value not illegal */
} /* clabWIFIAccessPointWMMCapability_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointWMMCapability_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMCapability_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointWMMCapability undo.
     */
    /*
     * copy clabWIFIAccessPointWMMCapability data
     * set rowreq_ctx->undo->clabWIFIAccessPointWMMCapability from rowreq_ctx->data.clabWIFIAccessPointWMMCapability
     */
    rowreq_ctx->undo->clabWIFIAccessPointWMMCapability = rowreq_ctx->data.clabWIFIAccessPointWMMCapability;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMCapability_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointWMMCapability_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointWMMCapability_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointWMMCapability_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMCapability_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointWMMCapability value.
     * set clabWIFIAccessPointWMMCapability value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointWMMCapability = clabWIFIAccessPointWMMCapability_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMCapability_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointWMMCapability_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMCapability_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointWMMCapability undo.
     */
    /*
     * copy clabWIFIAccessPointWMMCapability data
     * set rowreq_ctx->data.clabWIFIAccessPointWMMCapability from rowreq_ctx->undo->clabWIFIAccessPointWMMCapability
     */
    rowreq_ctx->data.clabWIFIAccessPointWMMCapability = rowreq_ctx->undo->clabWIFIAccessPointWMMCapability;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMCapability_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointUAPSDCapability
 * clabWIFIAccessPointUAPSDCapability is subid 9 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.9
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.UAPSDCapability.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointUAPSDCapability_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointUAPSDCapability_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointUAPSDCapability_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDCapability_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointUAPSDCapability value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointUAPSDCapability value not illegal */
} /* clabWIFIAccessPointUAPSDCapability_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointUAPSDCapability_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDCapability_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointUAPSDCapability undo.
     */
    /*
     * copy clabWIFIAccessPointUAPSDCapability data
     * set rowreq_ctx->undo->clabWIFIAccessPointUAPSDCapability from rowreq_ctx->data.clabWIFIAccessPointUAPSDCapability
     */
    rowreq_ctx->undo->clabWIFIAccessPointUAPSDCapability = rowreq_ctx->data.clabWIFIAccessPointUAPSDCapability;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDCapability_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointUAPSDCapability_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointUAPSDCapability_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointUAPSDCapability_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDCapability_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointUAPSDCapability value.
     * set clabWIFIAccessPointUAPSDCapability value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointUAPSDCapability = clabWIFIAccessPointUAPSDCapability_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDCapability_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointUAPSDCapability_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDCapability_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointUAPSDCapability undo.
     */
    /*
     * copy clabWIFIAccessPointUAPSDCapability data
     * set rowreq_ctx->data.clabWIFIAccessPointUAPSDCapability from rowreq_ctx->undo->clabWIFIAccessPointUAPSDCapability
     */
    rowreq_ctx->data.clabWIFIAccessPointUAPSDCapability = rowreq_ctx->undo->clabWIFIAccessPointUAPSDCapability;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDCapability_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointWMMEnable
 * clabWIFIAccessPointWMMEnable is subid 10 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.10
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.WMMEnable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointWMMEnable_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointWMMEnable_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointWMMEnable_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMEnable_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointWMMEnable value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointWMMEnable value not illegal */
} /* clabWIFIAccessPointWMMEnable_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointWMMEnable_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMEnable_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointWMMEnable undo.
     */
    /*
     * copy clabWIFIAccessPointWMMEnable data
     * set rowreq_ctx->undo->clabWIFIAccessPointWMMEnable from rowreq_ctx->data.clabWIFIAccessPointWMMEnable
     */
    rowreq_ctx->undo->clabWIFIAccessPointWMMEnable = rowreq_ctx->data.clabWIFIAccessPointWMMEnable;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMEnable_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointWMMEnable_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointWMMEnable_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointWMMEnable_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMEnable_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointWMMEnable value.
     * set clabWIFIAccessPointWMMEnable value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointWMMEnable = clabWIFIAccessPointWMMEnable_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMEnable_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointWMMEnable_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointWMMEnable_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointWMMEnable undo.
     */
    /*
     * copy clabWIFIAccessPointWMMEnable data
     * set rowreq_ctx->data.clabWIFIAccessPointWMMEnable from rowreq_ctx->undo->clabWIFIAccessPointWMMEnable
     */
    rowreq_ctx->data.clabWIFIAccessPointWMMEnable = rowreq_ctx->undo->clabWIFIAccessPointWMMEnable;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointWMMEnable_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointUAPSDEnable
 * clabWIFIAccessPointUAPSDEnable is subid 11 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.11
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.UAPSDEnable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointUAPSDEnable_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointUAPSDEnable_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointUAPSDEnable_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDEnable_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointUAPSDEnable value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointUAPSDEnable value not illegal */
} /* clabWIFIAccessPointUAPSDEnable_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointUAPSDEnable_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDEnable_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointUAPSDEnable undo.
     */
    /*
     * copy clabWIFIAccessPointUAPSDEnable data
     * set rowreq_ctx->undo->clabWIFIAccessPointUAPSDEnable from rowreq_ctx->data.clabWIFIAccessPointUAPSDEnable
     */
    rowreq_ctx->undo->clabWIFIAccessPointUAPSDEnable = rowreq_ctx->data.clabWIFIAccessPointUAPSDEnable;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDEnable_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointUAPSDEnable_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointUAPSDEnable_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointUAPSDEnable_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDEnable_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointUAPSDEnable value.
     * set clabWIFIAccessPointUAPSDEnable value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointUAPSDEnable = clabWIFIAccessPointUAPSDEnable_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDEnable_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointUAPSDEnable_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointUAPSDEnable_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointUAPSDEnable undo.
     */
    /*
     * copy clabWIFIAccessPointUAPSDEnable data
     * set rowreq_ctx->data.clabWIFIAccessPointUAPSDEnable from rowreq_ctx->undo->clabWIFIAccessPointUAPSDEnable
     */
    rowreq_ctx->data.clabWIFIAccessPointUAPSDEnable = rowreq_ctx->undo->clabWIFIAccessPointUAPSDEnable;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointUAPSDEnable_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointAssociatedDeviceNumberOfEntries
 * clabWIFIAccessPointAssociatedDeviceNumberOfEntries is subid 12 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.12
 * Description:
This object is defined in TR-181 Device.WiFi.AccessPoint{i}.AssociatedDeviceNumberOfEntries.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointAssociatedDeviceNumberOfEntries_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointAssociatedDeviceNumberOfEntries_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointAssociatedDeviceNumberOfEntries_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAssociatedDeviceNumberOfEntries_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointAssociatedDeviceNumberOfEntries value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointAssociatedDeviceNumberOfEntries value not illegal */
} /* clabWIFIAccessPointAssociatedDeviceNumberOfEntries_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointAssociatedDeviceNumberOfEntries undo.
     */
    /*
     * copy clabWIFIAccessPointAssociatedDeviceNumberOfEntries data
     * set rowreq_ctx->undo->clabWIFIAccessPointAssociatedDeviceNumberOfEntries from rowreq_ctx->data.clabWIFIAccessPointAssociatedDeviceNumberOfEntries
     */
    rowreq_ctx->undo->clabWIFIAccessPointAssociatedDeviceNumberOfEntries = rowreq_ctx->data.clabWIFIAccessPointAssociatedDeviceNumberOfEntries;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointAssociatedDeviceNumberOfEntries_val
 *        A u_long containing the new value.
 */
int
clabWIFIAccessPointAssociatedDeviceNumberOfEntries_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointAssociatedDeviceNumberOfEntries_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAssociatedDeviceNumberOfEntries_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointAssociatedDeviceNumberOfEntries value.
     * set clabWIFIAccessPointAssociatedDeviceNumberOfEntries value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointAssociatedDeviceNumberOfEntries = clabWIFIAccessPointAssociatedDeviceNumberOfEntries_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointAssociatedDeviceNumberOfEntries_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointAssociatedDeviceNumberOfEntries undo.
     */
    /*
     * copy clabWIFIAccessPointAssociatedDeviceNumberOfEntries data
     * set rowreq_ctx->data.clabWIFIAccessPointAssociatedDeviceNumberOfEntries from rowreq_ctx->undo->clabWIFIAccessPointAssociatedDeviceNumberOfEntries
     */
    rowreq_ctx->data.clabWIFIAccessPointAssociatedDeviceNumberOfEntries = rowreq_ctx->undo->clabWIFIAccessPointAssociatedDeviceNumberOfEntries;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointAssociatedDeviceNumberOfEntries_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAccessPointEntry.clabWIFIAccessPointRowStatus
 * clabWIFIAccessPointRowStatus is subid 13 of clabWIFIAccessPointEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.6.1.13
 * Description:
The status of this instance.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAccessPointRowStatus_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAccessPointTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAccessPointRowStatus_check_value( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointRowStatus_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRowStatus_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAccessPointRowStatus value.
     */

    return MFD_SUCCESS; /* clabWIFIAccessPointRowStatus value not illegal */
} /* clabWIFIAccessPointRowStatus_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAccessPointTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAccessPointTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAccessPointRowStatus_undo_setup( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRowStatus_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAccessPointRowStatus undo.
     */
    /*
     * copy clabWIFIAccessPointRowStatus data
     * set rowreq_ctx->undo->clabWIFIAccessPointRowStatus from rowreq_ctx->data.clabWIFIAccessPointRowStatus
     */
    rowreq_ctx->undo->clabWIFIAccessPointRowStatus = rowreq_ctx->data.clabWIFIAccessPointRowStatus;


    return MFD_SUCCESS;
} /* clabWIFIAccessPointRowStatus_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAccessPointRowStatus_val
 *        A long containing the new value.
 */
int
clabWIFIAccessPointRowStatus_set( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAccessPointRowStatus_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRowStatus_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAccessPointRowStatus value.
     * set clabWIFIAccessPointRowStatus value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAccessPointRowStatus = clabWIFIAccessPointRowStatus_val;

    return MFD_SUCCESS;
} /* clabWIFIAccessPointRowStatus_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAccessPointRowStatus_undo( clabWIFIAccessPointTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAccessPointTable:clabWIFIAccessPointRowStatus_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAccessPointRowStatus undo.
     */
    /*
     * copy clabWIFIAccessPointRowStatus data
     * set rowreq_ctx->data.clabWIFIAccessPointRowStatus from rowreq_ctx->undo->clabWIFIAccessPointRowStatus
     */
    rowreq_ctx->data.clabWIFIAccessPointRowStatus = rowreq_ctx->undo->clabWIFIAccessPointRowStatus;

    
    return MFD_SUCCESS;
} /* clabWIFIAccessPointRowStatus_undo */

/** @} */
