/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CLABWIFIASSOCIATEDDEVICETABLE_INTERFACE_H
#define CLABWIFIASSOCIATEDDEVICETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "clabWIFIAssociatedDeviceTable.h"

#if 0
/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _clabWIFIAssociatedDeviceTable_initialize_interface(clabWIFIAssociatedDeviceTable_registration * user_ctx,
                                    u_long flags);
void _clabWIFIAssociatedDeviceTable_shutdown_interface(clabWIFIAssociatedDeviceTable_registration * user_ctx);

clabWIFIAssociatedDeviceTable_registration *
clabWIFIAssociatedDeviceTable_registration_get( void );

clabWIFIAssociatedDeviceTable_registration *
clabWIFIAssociatedDeviceTable_registration_set( clabWIFIAssociatedDeviceTable_registration * newreg );

netsnmp_container *clabWIFIAssociatedDeviceTable_container_get( void );
int clabWIFIAssociatedDeviceTable_container_size( void );

u_int clabWIFIAssociatedDeviceTable_dirty_get( void );
void clabWIFIAssociatedDeviceTable_dirty_set( u_int status );

    clabWIFIAssociatedDeviceTable_rowreq_ctx * clabWIFIAssociatedDeviceTable_allocate_rowreq_ctx(void *);
void clabWIFIAssociatedDeviceTable_release_rowreq_ctx(clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx);

int clabWIFIAssociatedDeviceTable_index_to_oid(netsnmp_index *oid_idx,
                            clabWIFIAssociatedDeviceTable_mib_index *mib_idx);
int clabWIFIAssociatedDeviceTable_index_from_oid(netsnmp_index *oid_idx,
                              clabWIFIAssociatedDeviceTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void clabWIFIAssociatedDeviceTable_valid_columns_set(netsnmp_column_info *vc);
#endif
int
_clabWIFIAssociatedDeviceTable_set_column( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column );


#ifdef __cplusplus
}
#endif

#endif /* CLABWIFIASSOCIATEDDEVICETABLE_INTERFACE_H */
/** @} */
