/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CLABWIFIRADIOTABLE_INTERFACE_H
#define CLABWIFIRADIOTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "clabWIFIRadioTable.h"

#if 0
/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _clabWIFIRadioTable_initialize_interface(clabWIFIRadioTable_registration * user_ctx,
                                    u_long flags);
void _clabWIFIRadioTable_shutdown_interface(clabWIFIRadioTable_registration * user_ctx);

clabWIFIRadioTable_registration *
clabWIFIRadioTable_registration_get( void );

clabWIFIRadioTable_registration *
clabWIFIRadioTable_registration_set( clabWIFIRadioTable_registration * newreg );

netsnmp_container *clabWIFIRadioTable_container_get( void );
int clabWIFIRadioTable_container_size( void );

u_int clabWIFIRadioTable_dirty_get( void );
void clabWIFIRadioTable_dirty_set( u_int status );

    clabWIFIRadioTable_rowreq_ctx * clabWIFIRadioTable_allocate_rowreq_ctx(void *);
void clabWIFIRadioTable_release_rowreq_ctx(clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);

int clabWIFIRadioTable_index_to_oid(netsnmp_index *oid_idx,
                            clabWIFIRadioTable_mib_index *mib_idx);
int clabWIFIRadioTable_index_from_oid(netsnmp_index *oid_idx,
                              clabWIFIRadioTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void clabWIFIRadioTable_valid_columns_set(netsnmp_column_info *vc);
#endif
int
_clabWIFIRadioTable_set_column( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column );


#ifdef __cplusplus
}
#endif

#endif /* CLABWIFIRADIOTABLE_INTERFACE_H */
/** @} */
