/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef CLABWIFIRADIOTABLE_DATA_SET_H
#define CLABWIFIRADIOTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clabWIFIRadioTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CLAB-WIFI-MIB::clabWIFIRadioTable is subid 2 of clabWIFIObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.2, length: 12
*/


int clabWIFIRadioTable_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);
int clabWIFIRadioTable_undo_cleanup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);
int clabWIFIRadioTable_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);
int clabWIFIRadioTable_commit( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);
int clabWIFIRadioTable_undo_commit( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx);


int clabWIFIRadioEnable_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioEnable_val);
int clabWIFIRadioEnable_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioEnable_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioEnable_val );
int clabWIFIRadioEnable_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioStatus_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatus_val);
int clabWIFIRadioStatus_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioStatus_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatus_val );
int clabWIFIRadioStatus_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioAlias_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioAlias_val_ptr,  size_t clabWIFIRadioAlias_val_ptr_len);
int clabWIFIRadioAlias_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioAlias_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioAlias_val_ptr,  size_t clabWIFIRadioAlias_val_ptr_len );
int clabWIFIRadioAlias_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioName_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioName_val_ptr,  size_t clabWIFIRadioName_val_ptr_len);
int clabWIFIRadioName_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioName_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioName_val_ptr,  size_t clabWIFIRadioName_val_ptr_len );
int clabWIFIRadioName_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioLastChange_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioLastChange_val);
int clabWIFIRadioLastChange_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioLastChange_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioLastChange_val );
int clabWIFIRadioLastChange_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioLowerLayers_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioLowerLayers_val_ptr,  size_t clabWIFIRadioLowerLayers_val_ptr_len);
int clabWIFIRadioLowerLayers_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioLowerLayers_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioLowerLayers_val_ptr,  size_t clabWIFIRadioLowerLayers_val_ptr_len );
int clabWIFIRadioLowerLayers_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioUpstream_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioUpstream_val);
int clabWIFIRadioUpstream_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioUpstream_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioUpstream_val );
int clabWIFIRadioUpstream_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioMaxBitRate_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioMaxBitRate_val);
int clabWIFIRadioMaxBitRate_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioMaxBitRate_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioMaxBitRate_val );
int clabWIFIRadioMaxBitRate_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioSupportedFrequencyBands_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioSupportedFrequencyBands_val_ptr,  size_t clabWIFIRadioSupportedFrequencyBands_val_ptr_len);
int clabWIFIRadioSupportedFrequencyBands_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioSupportedFrequencyBands_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioSupportedFrequencyBands_val_ptr,  size_t clabWIFIRadioSupportedFrequencyBands_val_ptr_len );
int clabWIFIRadioSupportedFrequencyBands_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioOperatingFrequencyBand_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingFrequencyBand_val);
int clabWIFIRadioOperatingFrequencyBand_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioOperatingFrequencyBand_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingFrequencyBand_val );
int clabWIFIRadioOperatingFrequencyBand_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioSupportedStandards_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioSupportedStandards_val_ptr,  size_t clabWIFIRadioSupportedStandards_val_ptr_len);
int clabWIFIRadioSupportedStandards_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioSupportedStandards_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioSupportedStandards_val_ptr,  size_t clabWIFIRadioSupportedStandards_val_ptr_len );
int clabWIFIRadioSupportedStandards_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioOperatingStandards_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingStandards_val);
int clabWIFIRadioOperatingStandards_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioOperatingStandards_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingStandards_val );
int clabWIFIRadioOperatingStandards_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioPossibleChannels_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioPossibleChannels_val_ptr,  size_t clabWIFIRadioPossibleChannels_val_ptr_len);
int clabWIFIRadioPossibleChannels_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioPossibleChannels_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioPossibleChannels_val_ptr,  size_t clabWIFIRadioPossibleChannels_val_ptr_len );
int clabWIFIRadioPossibleChannels_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioChannelsInUse_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioChannelsInUse_val_ptr,  size_t clabWIFIRadioChannelsInUse_val_ptr_len);
int clabWIFIRadioChannelsInUse_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioChannelsInUse_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioChannelsInUse_val_ptr,  size_t clabWIFIRadioChannelsInUse_val_ptr_len );
int clabWIFIRadioChannelsInUse_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioChannel_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioChannel_val);
int clabWIFIRadioChannel_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioChannel_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioChannel_val );
int clabWIFIRadioChannel_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioAutoChannelSupported_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelSupported_val);
int clabWIFIRadioAutoChannelSupported_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioAutoChannelSupported_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelSupported_val );
int clabWIFIRadioAutoChannelSupported_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioAutoChannelEnable_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelEnable_val);
int clabWIFIRadioAutoChannelEnable_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioAutoChannelEnable_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelEnable_val );
int clabWIFIRadioAutoChannelEnable_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioAutoChannelRefreshPeriod_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelRefreshPeriod_val);
int clabWIFIRadioAutoChannelRefreshPeriod_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioAutoChannelRefreshPeriod_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioAutoChannelRefreshPeriod_val );
int clabWIFIRadioAutoChannelRefreshPeriod_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioOperatingChannelBandwidth_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingChannelBandwidth_val);
int clabWIFIRadioOperatingChannelBandwidth_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioOperatingChannelBandwidth_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioOperatingChannelBandwidth_val );
int clabWIFIRadioOperatingChannelBandwidth_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioExtensionChannel_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioExtensionChannel_val);
int clabWIFIRadioExtensionChannel_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioExtensionChannel_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioExtensionChannel_val );
int clabWIFIRadioExtensionChannel_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioGuardInterval_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioGuardInterval_val);
int clabWIFIRadioGuardInterval_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioGuardInterval_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioGuardInterval_val );
int clabWIFIRadioGuardInterval_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioMCS_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioMCS_val);
int clabWIFIRadioMCS_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioMCS_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioMCS_val );
int clabWIFIRadioMCS_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioTransmitPowerSupported_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioTransmitPowerSupported_val_ptr,  size_t clabWIFIRadioTransmitPowerSupported_val_ptr_len);
int clabWIFIRadioTransmitPowerSupported_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioTransmitPowerSupported_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioTransmitPowerSupported_val_ptr,  size_t clabWIFIRadioTransmitPowerSupported_val_ptr_len );
int clabWIFIRadioTransmitPowerSupported_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioTransmitPower_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioTransmitPower_val);
int clabWIFIRadioTransmitPower_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioTransmitPower_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioTransmitPower_val );
int clabWIFIRadioTransmitPower_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioIEEE80211hSupported_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioIEEE80211hSupported_val);
int clabWIFIRadioIEEE80211hSupported_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioIEEE80211hSupported_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioIEEE80211hSupported_val );
int clabWIFIRadioIEEE80211hSupported_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioIEEE80211hEnabled_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioIEEE80211hEnabled_val);
int clabWIFIRadioIEEE80211hEnabled_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioIEEE80211hEnabled_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioIEEE80211hEnabled_val );
int clabWIFIRadioIEEE80211hEnabled_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioRegulatoryDomain_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioRegulatoryDomain_val_ptr,  size_t clabWIFIRadioRegulatoryDomain_val_ptr_len);
int clabWIFIRadioRegulatoryDomain_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioRegulatoryDomain_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, char *clabWIFIRadioRegulatoryDomain_val_ptr,  size_t clabWIFIRadioRegulatoryDomain_val_ptr_len );
int clabWIFIRadioRegulatoryDomain_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioNoncontiguousChannel_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioNoncontiguousChannel_val);
int clabWIFIRadioNoncontiguousChannel_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioNoncontiguousChannel_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioNoncontiguousChannel_val );
int clabWIFIRadioNoncontiguousChannel_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioCarrierSenseThresholdInUse_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioCarrierSenseThresholdInUse_val);
int clabWIFIRadioCarrierSenseThresholdInUse_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioCarrierSenseThresholdInUse_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioCarrierSenseThresholdInUse_val );
int clabWIFIRadioCarrierSenseThresholdInUse_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioCarrierSenseThresholdRange_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioCarrierSenseThresholdRange_val);
int clabWIFIRadioCarrierSenseThresholdRange_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioCarrierSenseThresholdRange_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioCarrierSenseThresholdRange_val );
int clabWIFIRadioCarrierSenseThresholdRange_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioStatsChanUtilization_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsChanUtilization_val);
int clabWIFIRadioStatsChanUtilization_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioStatsChanUtilization_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsChanUtilization_val );
int clabWIFIRadioStatsChanUtilization_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioRtsCtsExchange_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioRtsCtsExchange_val);
int clabWIFIRadioRtsCtsExchange_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioRtsCtsExchange_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioRtsCtsExchange_val );
int clabWIFIRadioRtsCtsExchange_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioFrameAggregationLevel_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioFrameAggregationLevel_val);
int clabWIFIRadioFrameAggregationLevel_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioFrameAggregationLevel_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioFrameAggregationLevel_val );
int clabWIFIRadioFrameAggregationLevel_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioThroughput_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioThroughput_val);
int clabWIFIRadioThroughput_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioThroughput_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioThroughput_val );
int clabWIFIRadioThroughput_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );

int clabWIFIRadioPktErrorRateSTA_check_value( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioPktErrorRateSTA_val);
int clabWIFIRadioPktErrorRateSTA_undo_setup( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );
int clabWIFIRadioPktErrorRateSTA_set( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx, long clabWIFIRadioPktErrorRateSTA_val );
int clabWIFIRadioPktErrorRateSTA_undo( clabWIFIRadioTable_rowreq_ctx *rowreq_ctx );


int clabWIFIRadioTable_check_dependencies(clabWIFIRadioTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CLABWIFIRADIOTABLE_DATA_SET_H */
