/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef CLABWIFISSIDTABLE_DATA_SET_H
#define CLABWIFISSIDTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clabWIFISSIDTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CLAB-WIFI-MIB::clabWIFISSIDTable is subid 4 of clabWIFIObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.4, length: 12
*/


int clabWIFISSIDTable_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx);
int clabWIFISSIDTable_undo_cleanup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx);
int clabWIFISSIDTable_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx);
int clabWIFISSIDTable_commit( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx);
int clabWIFISSIDTable_undo_commit( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx);


int clabWIFISSIDEnable_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDEnable_val);
int clabWIFISSIDEnable_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDEnable_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDEnable_val );
int clabWIFISSIDEnable_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDStatus_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDStatus_val);
int clabWIFISSIDStatus_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDStatus_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDStatus_val );
int clabWIFISSIDStatus_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDAlias_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDAlias_val_ptr,  size_t clabWIFISSIDAlias_val_ptr_len);
int clabWIFISSIDAlias_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDAlias_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDAlias_val_ptr,  size_t clabWIFISSIDAlias_val_ptr_len );
int clabWIFISSIDAlias_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDName_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDName_val_ptr,  size_t clabWIFISSIDName_val_ptr_len);
int clabWIFISSIDName_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDName_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDName_val_ptr,  size_t clabWIFISSIDName_val_ptr_len );
int clabWIFISSIDName_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDLastChange_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDLastChange_val);
int clabWIFISSIDLastChange_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDLastChange_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDLastChange_val );
int clabWIFISSIDLastChange_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDLowerLayers_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDLowerLayers_val_ptr,  size_t clabWIFISSIDLowerLayers_val_ptr_len);
int clabWIFISSIDLowerLayers_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDLowerLayers_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDLowerLayers_val_ptr,  size_t clabWIFISSIDLowerLayers_val_ptr_len );
int clabWIFISSIDLowerLayers_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDBSSID_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDBSSID_val_ptr,  size_t clabWIFISSIDBSSID_val_ptr_len);
int clabWIFISSIDBSSID_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDBSSID_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDBSSID_val_ptr,  size_t clabWIFISSIDBSSID_val_ptr_len );
int clabWIFISSIDBSSID_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDMACAddress_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDMACAddress_val_ptr,  size_t clabWIFISSIDMACAddress_val_ptr_len);
int clabWIFISSIDMACAddress_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDMACAddress_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDMACAddress_val_ptr,  size_t clabWIFISSIDMACAddress_val_ptr_len );
int clabWIFISSIDMACAddress_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDSSID_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDSSID_val_ptr,  size_t clabWIFISSIDSSID_val_ptr_len);
int clabWIFISSIDSSID_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDSSID_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, char *clabWIFISSIDSSID_val_ptr,  size_t clabWIFISSIDSSID_val_ptr_len );
int clabWIFISSIDSSID_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );

int clabWIFISSIDRowStatus_check_value( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDRowStatus_val);
int clabWIFISSIDRowStatus_undo_setup( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );
int clabWIFISSIDRowStatus_set( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx, u_long clabWIFISSIDRowStatus_val );
int clabWIFISSIDRowStatus_undo( clabWIFISSIDTable_rowreq_ctx *rowreq_ctx );


int clabWIFISSIDTable_check_dependencies(clabWIFISSIDTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CLABWIFISSIDTABLE_DATA_SET_H */
