/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef CLABWIFISSIDTABLE_ENUMS_H
#define CLABWIFISSIDTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table clabWIFISSIDTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * clabWIFISSIDEnable (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * clabWIFISSIDStatus (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef CLABWIFISSIDSTATUS_ENUMS
#define CLABWIFISSIDSTATUS_ENUMS

#define CLABWIFISSIDSTATUS_UP  1 
#define CLABWIFISSIDSTATUS_DOWN  2 
#define CLABWIFISSIDSTATUS_UNKNOWN  4 
#define CLABWIFISSIDSTATUS_DORMANT  5 
#define CLABWIFISSIDSTATUS_NOTPRESENT  6 
#define CLABWIFISSIDSTATUS_LOWERLAYERDOWN  7 
#define CLABWIFISSIDSTATUS_ERROR  8 

#endif /* CLABWIFISSIDSTATUS_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * clabWIFISSIDRowStatus (RowStatus / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef ROWSTATUS_ENUMS
#define ROWSTATUS_ENUMS

#define ROWSTATUS_ACTIVE  1 
#define ROWSTATUS_NOTINSERVICE  2 
#define ROWSTATUS_NOTREADY  3 
#define ROWSTATUS_CREATEANDGO  4 
#define ROWSTATUS_CREATEANDWAIT  5 
#define ROWSTATUS_DESTROY  6 

#endif /* ROWSTATUS_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* CLABWIFISSIDTABLE_ENUMS_H */
