/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DOT11BSSTABLE_INTERFACE_H
#define DOT11BSSTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "dot11BssTable.h"

#if 0
/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _dot11BssTable_initialize_interface(dot11BssTable_registration * user_ctx,
                                    u_long flags);
void _dot11BssTable_shutdown_interface(dot11BssTable_registration * user_ctx);

dot11BssTable_registration *
dot11BssTable_registration_get( void );

dot11BssTable_registration *
dot11BssTable_registration_set( dot11BssTable_registration * newreg );

netsnmp_container *dot11BssTable_container_get( void );
int dot11BssTable_container_size( void );

u_int dot11BssTable_dirty_get( void );
void dot11BssTable_dirty_set( u_int status );

    dot11BssTable_rowreq_ctx * dot11BssTable_allocate_rowreq_ctx(void);
void dot11BssTable_release_rowreq_ctx(dot11BssTable_rowreq_ctx *rowreq_ctx);

int dot11BssTable_index_to_oid(netsnmp_index *oid_idx,
                            dot11BssTable_mib_index *mib_idx);
int dot11BssTable_index_from_oid(netsnmp_index *oid_idx,
                              dot11BssTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void dot11BssTable_valid_columns_set(netsnmp_column_info *vc);
#endif
int
_dot11BssTable_set_column( dot11BssTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column );


#ifdef __cplusplus
}
#endif

#endif /* DOT11BSSTABLE_INTERFACE_H */
/** @} */
