/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef WIFIASSOCSTATABLE_DATA_SET_H
#define WIFIASSOCSTATABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wifiAssocStaTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRCM-WIFI-MGMT-MIB::wifiAssocStaTable is subid 3 of wifiAssocStaDiagnostics.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4413.2.2.2.1.18.1.5.3, length: 15
*/


int wifiAssocStaTable_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx);
int wifiAssocStaTable_undo_cleanup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx);
int wifiAssocStaTable_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx);
int wifiAssocStaTable_commit( wifiAssocStaTable_rowreq_ctx *rowreq_ctx);
int wifiAssocStaTable_undo_commit( wifiAssocStaTable_rowreq_ctx *rowreq_ctx);


int wifiAssocStaRssi_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, long wifiAssocStaRssi_val);
int wifiAssocStaRssi_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaRssi_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, long wifiAssocStaRssi_val );
int wifiAssocStaRssi_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPhyRate_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, long wifiAssocStaPhyRate_val);
int wifiAssocStaPhyRate_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPhyRate_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, long wifiAssocStaPhyRate_val );
int wifiAssocStaPhyRate_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaMacAddress_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, char *wifiAssocStaMacAddress_val_ptr,  size_t wifiAssocStaMacAddress_val_ptr_len);
int wifiAssocStaMacAddress_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaMacAddress_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, char *wifiAssocStaMacAddress_val_ptr,  size_t wifiAssocStaMacAddress_val_ptr_len );
int wifiAssocStaMacAddress_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPRequested_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRequested_val);
int wifiAssocStaPRequested_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPRequested_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRequested_val );
int wifiAssocStaPRequested_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPStored_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPStored_val);
int wifiAssocStaPStored_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPStored_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPStored_val );
int wifiAssocStaPStored_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPDropped_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPDropped_val);
int wifiAssocStaPDropped_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPDropped_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPDropped_val );
int wifiAssocStaPDropped_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPRetried_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRetried_val);
int wifiAssocStaPRetried_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPRetried_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRetried_val );
int wifiAssocStaPRetried_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPUtilization_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPUtilization_val);
int wifiAssocStaPUtilization_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPUtilization_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPUtilization_val );
int wifiAssocStaPUtilization_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPQLength_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPQLength_val);
int wifiAssocStaPQLength_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPQLength_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPQLength_val );
int wifiAssocStaPQLength_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPRtsFail_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRtsFail_val);
int wifiAssocStaPRtsFail_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPRtsFail_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRtsFail_val );
int wifiAssocStaPRtsFail_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPRtryDrop_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRtryDrop_val);
int wifiAssocStaPRtryDrop_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPRtryDrop_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPRtryDrop_val );
int wifiAssocStaPRtryDrop_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPPSRetry_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPPSRetry_val);
int wifiAssocStaPPSRetry_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPPSRetry_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPPSRetry_val );
int wifiAssocStaPPSRetry_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPAcked_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPAcked_val);
int wifiAssocStaPAcked_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPAcked_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPAcked_val );
int wifiAssocStaPAcked_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPTput_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPTput_val);
int wifiAssocStaPTput_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPTput_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPTput_val );
int wifiAssocStaPTput_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaPPhyRate_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPPhyRate_val);
int wifiAssocStaPPhyRate_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaPPhyRate_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaPPhyRate_val );
int wifiAssocStaPPhyRate_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaTxBytes_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, U64 wifiAssocStaTxBytes_val);
int wifiAssocStaTxBytes_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaTxBytes_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, U64 wifiAssocStaTxBytes_val );
int wifiAssocStaTxBytes_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaRxBytes_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, U64 wifiAssocStaRxBytes_val);
int wifiAssocStaRxBytes_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaRxBytes_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, U64 wifiAssocStaRxBytes_val );
int wifiAssocStaRxBytes_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaTxRateLimit_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaTxRateLimit_val);
int wifiAssocStaTxRateLimit_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaTxRateLimit_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaTxRateLimit_val );
int wifiAssocStaTxRateLimit_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );

int wifiAssocStaRxRateLimit_check_value( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaRxRateLimit_val);
int wifiAssocStaRxRateLimit_undo_setup( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );
int wifiAssocStaRxRateLimit_set( wifiAssocStaTable_rowreq_ctx *rowreq_ctx, u_long wifiAssocStaRxRateLimit_val );
int wifiAssocStaRxRateLimit_undo( wifiAssocStaTable_rowreq_ctx *rowreq_ctx );


int wifiAssocStaTable_check_dependencies(wifiAssocStaTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* WIFIASSOCSTATABLE_DATA_SET_H */
