/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef WIFIBSSWPATABLE_ENUMS_H
#define WIFIBSSWPATABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table wifiBssWpaTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * wifiBssWpaAlgorithm (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef WIFIBSSWPAALGORITHM_ENUMS
#define WIFIBSSWPAALGORITHM_ENUMS

#define WIFIBSSWPAALGORITHM_NONE  1 
#define WIFIBSSWPAALGORITHM_AES  2 
#define WIFIBSSWPAALGORITHM_TKIPPLUSAES  3 

#endif /* WIFIBSSWPAALGORITHM_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* WIFIBSSWPATABLE_ENUMS_H */
