/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "clabWIFIRadioStatsTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clabWIFIRadioStatsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CLAB-WIFI-MIB::clabWIFIRadioStatsTable is subid 3 of clabWIFIObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3, length: 12
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * clabWIFIRadioStatsTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * clabWIFIRadioStatsTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIRadioStatsTable_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup clabWIFIRadioStatsTable undo.
     * set up clabWIFIRadioStatsTable undo information, in preparation for a set.
     * Undo storage is in (* clabWIFIRadioStatsDiscardPacketsReceived_val_ptr )*
     */

    return rc;
} /* clabWIFIRadioStatsTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIRadioStatsTable_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> clabWIFIRadioStatsTable undo.
     * clabWIFIRadioStatsTable undo information, in response to a failed set.
     * Undo storage is in (* clabWIFIRadioStatsDiscardPacketsReceived_val_ptr )*
     */

    return rc;
} /* clabWIFIRadioStatsTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIRadioStatsTable_undo_cleanup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup clabWIFIRadioStatsTable undo.
     * Undo storage is in (* clabWIFIRadioStatsDiscardPacketsReceived_val_ptr )*
     */

    return rc;
} /* clabWIFIRadioStatsTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIRadioStatsTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIRadioStatsTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIRadioStatsTable_commit( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit clabWIFIRadioStatsTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_CLABWIFIRADIOSTATSBYTESSENT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSBYTESSENT_FLAG; /* clear clabWIFIRadioStatsBytesSent */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsBytesSent.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsBytesSent commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsBytesSent
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSBYTESSENT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSBYTESRECEIVED_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSBYTESRECEIVED_FLAG; /* clear clabWIFIRadioStatsBytesReceived */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsBytesReceived.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsBytesReceived commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsBytesReceived
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSBYTESRECEIVED_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSPACKETSSENT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSPACKETSSENT_FLAG; /* clear clabWIFIRadioStatsPacketsSent */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsPacketsSent.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsPacketsSent commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsPacketsSent
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSPACKETSSENT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSPACKETSRECEIVED_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSPACKETSRECEIVED_FLAG; /* clear clabWIFIRadioStatsPacketsReceived */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsPacketsReceived.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsPacketsReceived commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsPacketsReceived
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSPACKETSRECEIVED_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSERRORSSENT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSERRORSSENT_FLAG; /* clear clabWIFIRadioStatsErrorsSent */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsErrorsSent.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsErrorsSent commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsErrorsSent
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSERRORSSENT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSERRORSRECEIVED_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSERRORSRECEIVED_FLAG; /* clear clabWIFIRadioStatsErrorsReceived */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsErrorsReceived.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsErrorsReceived commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsErrorsReceived
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSERRORSRECEIVED_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSSENT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSSENT_FLAG; /* clear clabWIFIRadioStatsDiscardPacketsSent */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsDiscardPacketsSent.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsDiscardPacketsSent commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsDiscardPacketsSent
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSSENT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSRECEIVED_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSRECEIVED_FLAG; /* clear clabWIFIRadioStatsDiscardPacketsReceived */
       /*
        * TODO:482:o: |-> commit column clabWIFIRadioStatsDiscardPacketsReceived.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIRadioStatsTable column clabWIFIRadioStatsDiscardPacketsReceived commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIRadioStatsDiscardPacketsReceived
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIRADIOSTATSDISCARDPACKETSRECEIVED_FLAG;
       }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* clabWIFIRadioStatsTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIRadioStatsTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIRadioStatsTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIRadioStatsTable_undo_commit( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo clabWIFIRadioStatsTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* clabWIFIRadioStatsTable_undo_commit */

/*
 * TODO:440:M: Implement clabWIFIRadioStatsTable node value checks.
 * TODO:450:M: Implement clabWIFIRadioStatsTable undo functions.
 * TODO:460:M: Implement clabWIFIRadioStatsTable set functions.
 * TODO:480:M: Implement clabWIFIRadioStatsTable commit functions.
 */
/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsBytesSent
 * clabWIFIRadioStatsBytesSent is subid 1 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.1
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.BytesSent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsBytesSent_val
 *        A U64 containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsBytesSent_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsBytesSent_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesSent_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsBytesSent value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsBytesSent value not illegal */
} /* clabWIFIRadioStatsBytesSent_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsBytesSent_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesSent_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsBytesSent undo.
     */
    /*
     * copy clabWIFIRadioStatsBytesSent data
     * set rowreq_ctx->undo->clabWIFIRadioStatsBytesSent from rowreq_ctx->data.clabWIFIRadioStatsBytesSent
     */
    rowreq_ctx->undo->clabWIFIRadioStatsBytesSent = rowreq_ctx->data.clabWIFIRadioStatsBytesSent;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesSent_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsBytesSent_val
 *        A U64 containing the new value.
 */
int
clabWIFIRadioStatsBytesSent_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsBytesSent_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesSent_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsBytesSent value.
     * set clabWIFIRadioStatsBytesSent value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsBytesSent = clabWIFIRadioStatsBytesSent_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesSent_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsBytesSent_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesSent_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsBytesSent undo.
     */
    /*
     * copy clabWIFIRadioStatsBytesSent data
     * set rowreq_ctx->data.clabWIFIRadioStatsBytesSent from rowreq_ctx->undo->clabWIFIRadioStatsBytesSent
     */
    rowreq_ctx->data.clabWIFIRadioStatsBytesSent = rowreq_ctx->undo->clabWIFIRadioStatsBytesSent;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesSent_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsBytesReceived
 * clabWIFIRadioStatsBytesReceived is subid 2 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.2
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.BytesReceived.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsBytesReceived_val
 *        A U64 containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsBytesReceived_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsBytesReceived_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesReceived_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsBytesReceived value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsBytesReceived value not illegal */
} /* clabWIFIRadioStatsBytesReceived_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsBytesReceived_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesReceived_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsBytesReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsBytesReceived data
     * set rowreq_ctx->undo->clabWIFIRadioStatsBytesReceived from rowreq_ctx->data.clabWIFIRadioStatsBytesReceived
     */
    rowreq_ctx->undo->clabWIFIRadioStatsBytesReceived = rowreq_ctx->data.clabWIFIRadioStatsBytesReceived;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesReceived_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsBytesReceived_val
 *        A U64 containing the new value.
 */
int
clabWIFIRadioStatsBytesReceived_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsBytesReceived_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesReceived_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsBytesReceived value.
     * set clabWIFIRadioStatsBytesReceived value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsBytesReceived = clabWIFIRadioStatsBytesReceived_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesReceived_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsBytesReceived_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsBytesReceived_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsBytesReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsBytesReceived data
     * set rowreq_ctx->data.clabWIFIRadioStatsBytesReceived from rowreq_ctx->undo->clabWIFIRadioStatsBytesReceived
     */
    rowreq_ctx->data.clabWIFIRadioStatsBytesReceived = rowreq_ctx->undo->clabWIFIRadioStatsBytesReceived;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsBytesReceived_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsPacketsSent
 * clabWIFIRadioStatsPacketsSent is subid 3 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.3
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.PacketsSent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsPacketsSent_val
 *        A U64 containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsPacketsSent_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsPacketsSent_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsSent_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsPacketsSent value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsPacketsSent value not illegal */
} /* clabWIFIRadioStatsPacketsSent_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsPacketsSent_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsSent_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsPacketsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsPacketsSent data
     * set rowreq_ctx->undo->clabWIFIRadioStatsPacketsSent from rowreq_ctx->data.clabWIFIRadioStatsPacketsSent
     */
    rowreq_ctx->undo->clabWIFIRadioStatsPacketsSent = rowreq_ctx->data.clabWIFIRadioStatsPacketsSent;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsSent_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsPacketsSent_val
 *        A U64 containing the new value.
 */
int
clabWIFIRadioStatsPacketsSent_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsPacketsSent_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsSent_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsPacketsSent value.
     * set clabWIFIRadioStatsPacketsSent value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsPacketsSent = clabWIFIRadioStatsPacketsSent_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsSent_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsPacketsSent_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsSent_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsPacketsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsPacketsSent data
     * set rowreq_ctx->data.clabWIFIRadioStatsPacketsSent from rowreq_ctx->undo->clabWIFIRadioStatsPacketsSent
     */
    rowreq_ctx->data.clabWIFIRadioStatsPacketsSent = rowreq_ctx->undo->clabWIFIRadioStatsPacketsSent;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsSent_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsPacketsReceived
 * clabWIFIRadioStatsPacketsReceived is subid 4 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.4
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.PacketsReceived.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsPacketsReceived_val
 *        A U64 containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsPacketsReceived_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsPacketsReceived_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsReceived_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsPacketsReceived value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsPacketsReceived value not illegal */
} /* clabWIFIRadioStatsPacketsReceived_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsPacketsReceived_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsReceived_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsPacketsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsPacketsReceived data
     * set rowreq_ctx->undo->clabWIFIRadioStatsPacketsReceived from rowreq_ctx->data.clabWIFIRadioStatsPacketsReceived
     */
    rowreq_ctx->undo->clabWIFIRadioStatsPacketsReceived = rowreq_ctx->data.clabWIFIRadioStatsPacketsReceived;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsReceived_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsPacketsReceived_val
 *        A U64 containing the new value.
 */
int
clabWIFIRadioStatsPacketsReceived_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, U64 clabWIFIRadioStatsPacketsReceived_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsReceived_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsPacketsReceived value.
     * set clabWIFIRadioStatsPacketsReceived value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsPacketsReceived = clabWIFIRadioStatsPacketsReceived_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsReceived_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsPacketsReceived_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsPacketsReceived_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsPacketsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsPacketsReceived data
     * set rowreq_ctx->data.clabWIFIRadioStatsPacketsReceived from rowreq_ctx->undo->clabWIFIRadioStatsPacketsReceived
     */
    rowreq_ctx->data.clabWIFIRadioStatsPacketsReceived = rowreq_ctx->undo->clabWIFIRadioStatsPacketsReceived;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsPacketsReceived_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsErrorsSent
 * clabWIFIRadioStatsErrorsSent is subid 5 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.5
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.ErrorsSent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsErrorsSent_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsErrorsSent_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsErrorsSent_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsSent_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsErrorsSent value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsErrorsSent value not illegal */
} /* clabWIFIRadioStatsErrorsSent_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsErrorsSent_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsSent_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsErrorsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsErrorsSent data
     * set rowreq_ctx->undo->clabWIFIRadioStatsErrorsSent from rowreq_ctx->data.clabWIFIRadioStatsErrorsSent
     */
    rowreq_ctx->undo->clabWIFIRadioStatsErrorsSent = rowreq_ctx->data.clabWIFIRadioStatsErrorsSent;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsSent_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsErrorsSent_val
 *        A u_long containing the new value.
 */
int
clabWIFIRadioStatsErrorsSent_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsErrorsSent_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsSent_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsErrorsSent value.
     * set clabWIFIRadioStatsErrorsSent value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsErrorsSent = clabWIFIRadioStatsErrorsSent_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsSent_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsErrorsSent_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsSent_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsErrorsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsErrorsSent data
     * set rowreq_ctx->data.clabWIFIRadioStatsErrorsSent from rowreq_ctx->undo->clabWIFIRadioStatsErrorsSent
     */
    rowreq_ctx->data.clabWIFIRadioStatsErrorsSent = rowreq_ctx->undo->clabWIFIRadioStatsErrorsSent;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsSent_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsErrorsReceived
 * clabWIFIRadioStatsErrorsReceived is subid 6 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.6
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.ErrorsReceived.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsErrorsReceived_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsErrorsReceived_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsErrorsReceived_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsReceived_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsErrorsReceived value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsErrorsReceived value not illegal */
} /* clabWIFIRadioStatsErrorsReceived_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsErrorsReceived_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsReceived_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsErrorsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsErrorsReceived data
     * set rowreq_ctx->undo->clabWIFIRadioStatsErrorsReceived from rowreq_ctx->data.clabWIFIRadioStatsErrorsReceived
     */
    rowreq_ctx->undo->clabWIFIRadioStatsErrorsReceived = rowreq_ctx->data.clabWIFIRadioStatsErrorsReceived;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsReceived_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsErrorsReceived_val
 *        A u_long containing the new value.
 */
int
clabWIFIRadioStatsErrorsReceived_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsErrorsReceived_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsReceived_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsErrorsReceived value.
     * set clabWIFIRadioStatsErrorsReceived value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsErrorsReceived = clabWIFIRadioStatsErrorsReceived_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsReceived_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsErrorsReceived_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsErrorsReceived_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsErrorsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsErrorsReceived data
     * set rowreq_ctx->data.clabWIFIRadioStatsErrorsReceived from rowreq_ctx->undo->clabWIFIRadioStatsErrorsReceived
     */
    rowreq_ctx->data.clabWIFIRadioStatsErrorsReceived = rowreq_ctx->undo->clabWIFIRadioStatsErrorsReceived;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsErrorsReceived_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsDiscardPacketsSent
 * clabWIFIRadioStatsDiscardPacketsSent is subid 7 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.7
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.DiscardPacketsSent.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsDiscardPacketsSent_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsDiscardPacketsSent_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsDiscardPacketsSent_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsSent_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsDiscardPacketsSent value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsDiscardPacketsSent value not illegal */
} /* clabWIFIRadioStatsDiscardPacketsSent_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsDiscardPacketsSent_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsSent_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsDiscardPacketsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsDiscardPacketsSent data
     * set rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsSent from rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsSent
     */
    rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsSent = rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsSent;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsSent_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsDiscardPacketsSent_val
 *        A u_long containing the new value.
 */
int
clabWIFIRadioStatsDiscardPacketsSent_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsDiscardPacketsSent_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsSent_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsDiscardPacketsSent value.
     * set clabWIFIRadioStatsDiscardPacketsSent value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsSent = clabWIFIRadioStatsDiscardPacketsSent_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsSent_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsDiscardPacketsSent_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsSent_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsDiscardPacketsSent undo.
     */
    /*
     * copy clabWIFIRadioStatsDiscardPacketsSent data
     * set rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsSent from rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsSent
     */
    rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsSent = rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsSent;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsSent_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIRadioStatsEntry.clabWIFIRadioStatsDiscardPacketsReceived
 * clabWIFIRadioStatsDiscardPacketsReceived is subid 8 of clabWIFIRadioStatsEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.3.1.8
 * Description:
This object is defined in TR-181 Device.WiFi.Radio.{i}.Stats.DiscardPacketsReceived.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIRadioStatsDiscardPacketsReceived_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIRadioStatsTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIRadioStatsDiscardPacketsReceived_check_value( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsDiscardPacketsReceived_val)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsReceived_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIRadioStatsDiscardPacketsReceived value.
     */

    return MFD_SUCCESS; /* clabWIFIRadioStatsDiscardPacketsReceived value not illegal */
} /* clabWIFIRadioStatsDiscardPacketsReceived_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIRadioStatsTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIRadioStatsTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIRadioStatsDiscardPacketsReceived_undo_setup( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsReceived_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIRadioStatsDiscardPacketsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsDiscardPacketsReceived data
     * set rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsReceived from rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsReceived
     */
    rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsReceived = rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsReceived;


    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsReceived_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIRadioStatsDiscardPacketsReceived_val
 *        A u_long containing the new value.
 */
int
clabWIFIRadioStatsDiscardPacketsReceived_set( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIRadioStatsDiscardPacketsReceived_val )
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsReceived_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIRadioStatsDiscardPacketsReceived value.
     * set clabWIFIRadioStatsDiscardPacketsReceived value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsReceived = clabWIFIRadioStatsDiscardPacketsReceived_val;

    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsReceived_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIRadioStatsDiscardPacketsReceived_undo( clabWIFIRadioStatsTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIRadioStatsTable:clabWIFIRadioStatsDiscardPacketsReceived_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIRadioStatsDiscardPacketsReceived undo.
     */
    /*
     * copy clabWIFIRadioStatsDiscardPacketsReceived data
     * set rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsReceived from rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsReceived
     */
    rowreq_ctx->data.clabWIFIRadioStatsDiscardPacketsReceived = rowreq_ctx->undo->clabWIFIRadioStatsDiscardPacketsReceived;

    
    return MFD_SUCCESS;
} /* clabWIFIRadioStatsDiscardPacketsReceived_undo */

/** @} */
