/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "clabWIFIAssociatedDeviceTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clabWIFIAssociatedDeviceTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceTable is subid 9 of clabWIFIObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9, length: 12
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * clabWIFIAssociatedDeviceTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * clabWIFIAssociatedDeviceTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIAssociatedDeviceTable_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup clabWIFIAssociatedDeviceTable undo.
     * set up clabWIFIAssociatedDeviceTable undo information, in preparation for a set.
     * Undo storage is in (* clabWIFIAssociatedDeviceMaxNumOfStations_val_ptr )*
     */

    return rc;
} /* clabWIFIAssociatedDeviceTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
clabWIFIAssociatedDeviceTable_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> clabWIFIAssociatedDeviceTable undo.
     * clabWIFIAssociatedDeviceTable undo information, in response to a failed set.
     * Undo storage is in (* clabWIFIAssociatedDeviceMaxNumOfStations_val_ptr )*
     */

    return rc;
} /* clabWIFIAssociatedDeviceTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAssociatedDeviceTable_undo_cleanup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup clabWIFIAssociatedDeviceTable undo.
     * Undo storage is in (* clabWIFIAssociatedDeviceMaxNumOfStations_val_ptr )*
     */

    return rc;
} /* clabWIFIAssociatedDeviceTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIAssociatedDeviceTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIAssociatedDeviceTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAssociatedDeviceTable_commit( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit clabWIFIAssociatedDeviceTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICEMACADDRESS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICEMACADDRESS_FLAG; /* clear clabWIFIAssociatedDeviceMACAddress */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceMACAddress.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceMACAddress commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceMACAddress
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICEMACADDRESS_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICEAUTHENTICATIONSTATE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICEAUTHENTICATIONSTATE_FLAG; /* clear clabWIFIAssociatedDeviceAuthenticationState */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceAuthenticationState.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceAuthenticationState commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceAuthenticationState
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICEAUTHENTICATIONSTATE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATADOWNLINKRATE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATADOWNLINKRATE_FLAG; /* clear clabWIFIAssociatedDeviceLastDataDownlinkRate */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceLastDataDownlinkRate.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceLastDataDownlinkRate commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceLastDataDownlinkRate
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATADOWNLINKRATE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATAUPLINKRATE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATAUPLINKRATE_FLAG; /* clear clabWIFIAssociatedDeviceLastDataUplinkRate */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceLastDataUplinkRate.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceLastDataUplinkRate commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceLastDataUplinkRate
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICELASTDATAUPLINKRATE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICESIGNALSTRENGTH_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICESIGNALSTRENGTH_FLAG; /* clear clabWIFIAssociatedDeviceSignalStrength */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceSignalStrength.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceSignalStrength commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceSignalStrength
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICESIGNALSTRENGTH_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICERETRANSMISSIONS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICERETRANSMISSIONS_FLAG; /* clear clabWIFIAssociatedDeviceRetransmissions */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceRetransmissions.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceRetransmissions commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceRetransmissions
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICERETRANSMISSIONS_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICEACTIVE_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICEACTIVE_FLAG; /* clear clabWIFIAssociatedDeviceActive */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceActive.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceActive commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceActive
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICEACTIVE_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICEMAXPACKETRETRYCOUNT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICEMAXPACKETRETRYCOUNT_FLAG; /* clear clabWIFIAssociatedDeviceMaxPacketRetryCount */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceMaxPacketRetryCount.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceMaxPacketRetryCount commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceMaxPacketRetryCount
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICEMAXPACKETRETRYCOUNT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICESTATIONCOUNT_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICESTATIONCOUNT_FLAG; /* clear clabWIFIAssociatedDeviceStationCount */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceStationCount.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceStationCount commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceStationCount
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICESTATIONCOUNT_FLAG;
       }
    }

    if (save_flags & COLUMN_CLABWIFIASSOCIATEDDEVICEMAXNUMOFSTATIONS_FLAG) {
       save_flags &= ~COLUMN_CLABWIFIASSOCIATEDDEVICEMAXNUMOFSTATIONS_FLAG; /* clear clabWIFIAssociatedDeviceMaxNumOfStations */
       /*
        * TODO:482:o: |-> commit column clabWIFIAssociatedDeviceMaxNumOfStations.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"clabWIFIAssociatedDeviceTable column clabWIFIAssociatedDeviceMaxNumOfStations commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo clabWIFIAssociatedDeviceMaxNumOfStations
             */
            rowreq_ctx->column_set_flags |= COLUMN_CLABWIFIASSOCIATEDDEVICEMAXNUMOFSTATIONS_FLAG;
       }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* clabWIFIAssociatedDeviceTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * clabWIFIAssociatedDeviceTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param clabWIFIAssociatedDeviceTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
clabWIFIAssociatedDeviceTable_undo_commit( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo clabWIFIAssociatedDeviceTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* clabWIFIAssociatedDeviceTable_undo_commit */

/*
 * TODO:440:M: Implement clabWIFIAssociatedDeviceTable node value checks.
 * TODO:450:M: Implement clabWIFIAssociatedDeviceTable undo functions.
 * TODO:460:M: Implement clabWIFIAssociatedDeviceTable set functions.
 * TODO:480:M: Implement clabWIFIAssociatedDeviceTable commit functions.
 */
/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceMACAddress
 * clabWIFIAssociatedDeviceMACAddress is subid 2 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.2
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.MACAddress.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 1x:
 *
 * Ranges:  6;
 *
 * Its syntax is MacAddress (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 6)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceMACAddress_val_ptr
 *        A char containing the new value.
 * @param clabWIFIAssociatedDeviceMACAddress_val_ptr_len
 *        The size (in bytes) of the data pointed to by clabWIFIAssociatedDeviceMACAddress_val_ptr
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_OCTET_STR
 *    The length is < sizeof(rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress).
 *    The length is in (one of) the range set(s):  6
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceMACAddress_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, char *clabWIFIAssociatedDeviceMACAddress_val_ptr,  size_t clabWIFIAssociatedDeviceMACAddress_val_ptr_len)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMACAddress_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != clabWIFIAssociatedDeviceMACAddress_val_ptr);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceMACAddress value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceMACAddress value not illegal */
} /* clabWIFIAssociatedDeviceMACAddress_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceMACAddress_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMACAddress_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceMACAddress undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMACAddress and clabWIFIAssociatedDeviceMACAddress_len data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress from rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress
     */
    memcpy( rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress, rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress,
            (rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress_len * sizeof(rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress[0])));
    rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress_len = rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress_len;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMACAddress_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceMACAddress_val_ptr
 *        A char containing the new value.
 * @param clabWIFIAssociatedDeviceMACAddress_val_ptr_len
 *        The size (in bytes) of the data pointed to by clabWIFIAssociatedDeviceMACAddress_val_ptr
 */
int
clabWIFIAssociatedDeviceMACAddress_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, char *clabWIFIAssociatedDeviceMACAddress_val_ptr,  size_t clabWIFIAssociatedDeviceMACAddress_val_ptr_len )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMACAddress_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != clabWIFIAssociatedDeviceMACAddress_val_ptr);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceMACAddress value.
     * set clabWIFIAssociatedDeviceMACAddress value in rowreq_ctx->data
     */
    memcpy( rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress, clabWIFIAssociatedDeviceMACAddress_val_ptr, clabWIFIAssociatedDeviceMACAddress_val_ptr_len );
    /** convert bytes to number of char */
    rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress_len = clabWIFIAssociatedDeviceMACAddress_val_ptr_len / sizeof(clabWIFIAssociatedDeviceMACAddress_val_ptr[0]);

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMACAddress_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceMACAddress_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMACAddress_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceMACAddress undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMACAddress and clabWIFIAssociatedDeviceMACAddress_len data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress from rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress
     */
    memcpy( rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress, rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress,
            (rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress_len * sizeof(rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress[0])));
    rowreq_ctx->data.clabWIFIAssociatedDeviceMACAddress_len = rowreq_ctx->undo->clabWIFIAssociatedDeviceMACAddress_len;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMACAddress_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceAuthenticationState
 * clabWIFIAssociatedDeviceAuthenticationState is subid 3 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.3
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.AuthenticationState.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceAuthenticationState_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceAuthenticationState_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceAuthenticationState_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceAuthenticationState_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceAuthenticationState value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceAuthenticationState value not illegal */
} /* clabWIFIAssociatedDeviceAuthenticationState_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceAuthenticationState_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceAuthenticationState_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceAuthenticationState undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceAuthenticationState data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceAuthenticationState from rowreq_ctx->data.clabWIFIAssociatedDeviceAuthenticationState
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceAuthenticationState = rowreq_ctx->data.clabWIFIAssociatedDeviceAuthenticationState;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceAuthenticationState_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceAuthenticationState_val
 *        A long containing the new value.
 */
int
clabWIFIAssociatedDeviceAuthenticationState_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceAuthenticationState_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceAuthenticationState_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceAuthenticationState value.
     * set clabWIFIAssociatedDeviceAuthenticationState value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceAuthenticationState = clabWIFIAssociatedDeviceAuthenticationState_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceAuthenticationState_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceAuthenticationState_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceAuthenticationState_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceAuthenticationState undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceAuthenticationState data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceAuthenticationState from rowreq_ctx->undo->clabWIFIAssociatedDeviceAuthenticationState
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceAuthenticationState = rowreq_ctx->undo->clabWIFIAssociatedDeviceAuthenticationState;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceAuthenticationState_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceLastDataDownlinkRate
 * clabWIFIAssociatedDeviceLastDataDownlinkRate is subid 4 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.4
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.LastDataDownlinkRate.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  1000 - 600000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceLastDataDownlinkRate_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  1000 - 600000
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceLastDataDownlinkRate_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceLastDataDownlinkRate_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataDownlinkRate_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceLastDataDownlinkRate value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceLastDataDownlinkRate value not illegal */
} /* clabWIFIAssociatedDeviceLastDataDownlinkRate_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceLastDataDownlinkRate_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataDownlinkRate_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceLastDataDownlinkRate undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceLastDataDownlinkRate data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataDownlinkRate from rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataDownlinkRate
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataDownlinkRate = rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataDownlinkRate;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataDownlinkRate_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceLastDataDownlinkRate_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceLastDataDownlinkRate_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceLastDataDownlinkRate_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataDownlinkRate_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceLastDataDownlinkRate value.
     * set clabWIFIAssociatedDeviceLastDataDownlinkRate value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataDownlinkRate = clabWIFIAssociatedDeviceLastDataDownlinkRate_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataDownlinkRate_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceLastDataDownlinkRate_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataDownlinkRate_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceLastDataDownlinkRate undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceLastDataDownlinkRate data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataDownlinkRate from rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataDownlinkRate
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataDownlinkRate = rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataDownlinkRate;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataDownlinkRate_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceLastDataUplinkRate
 * clabWIFIAssociatedDeviceLastDataUplinkRate is subid 5 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.5
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.DeviceLastDataUplinkRate.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  1000 - 600000;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceLastDataUplinkRate_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  1000 - 600000
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceLastDataUplinkRate_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceLastDataUplinkRate_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataUplinkRate_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceLastDataUplinkRate value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceLastDataUplinkRate value not illegal */
} /* clabWIFIAssociatedDeviceLastDataUplinkRate_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceLastDataUplinkRate_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataUplinkRate_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceLastDataUplinkRate undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceLastDataUplinkRate data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataUplinkRate from rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataUplinkRate
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataUplinkRate = rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataUplinkRate;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataUplinkRate_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceLastDataUplinkRate_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceLastDataUplinkRate_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceLastDataUplinkRate_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataUplinkRate_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceLastDataUplinkRate value.
     * set clabWIFIAssociatedDeviceLastDataUplinkRate value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataUplinkRate = clabWIFIAssociatedDeviceLastDataUplinkRate_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataUplinkRate_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceLastDataUplinkRate_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceLastDataUplinkRate_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceLastDataUplinkRate undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceLastDataUplinkRate data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataUplinkRate from rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataUplinkRate
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceLastDataUplinkRate = rowreq_ctx->undo->clabWIFIAssociatedDeviceLastDataUplinkRate;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceLastDataUplinkRate_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceSignalStrength
 * clabWIFIAssociatedDeviceSignalStrength is subid 6 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.6
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.SignalStrength.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  -200 - 0;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceSignalStrength_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is in (one of) the range set(s):  -200 - 0
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceSignalStrength_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, long clabWIFIAssociatedDeviceSignalStrength_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceSignalStrength_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceSignalStrength value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceSignalStrength value not illegal */
} /* clabWIFIAssociatedDeviceSignalStrength_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceSignalStrength_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceSignalStrength_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceSignalStrength undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceSignalStrength data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceSignalStrength from rowreq_ctx->data.clabWIFIAssociatedDeviceSignalStrength
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceSignalStrength = rowreq_ctx->data.clabWIFIAssociatedDeviceSignalStrength;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceSignalStrength_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceSignalStrength_val
 *        A long containing the new value.
 */
int
clabWIFIAssociatedDeviceSignalStrength_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, long clabWIFIAssociatedDeviceSignalStrength_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceSignalStrength_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceSignalStrength value.
     * set clabWIFIAssociatedDeviceSignalStrength value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceSignalStrength = clabWIFIAssociatedDeviceSignalStrength_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceSignalStrength_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceSignalStrength_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceSignalStrength_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceSignalStrength undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceSignalStrength data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceSignalStrength from rowreq_ctx->undo->clabWIFIAssociatedDeviceSignalStrength
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceSignalStrength = rowreq_ctx->undo->clabWIFIAssociatedDeviceSignalStrength;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceSignalStrength_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceRetransmissions
 * clabWIFIAssociatedDeviceRetransmissions is subid 7 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.7
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.Retransmissions.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 100;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceRetransmissions_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *    The value is in (one of) the range set(s):  0 - 100
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceRetransmissions_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceRetransmissions_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceRetransmissions_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceRetransmissions value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceRetransmissions value not illegal */
} /* clabWIFIAssociatedDeviceRetransmissions_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceRetransmissions_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceRetransmissions_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceRetransmissions undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceRetransmissions data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceRetransmissions from rowreq_ctx->data.clabWIFIAssociatedDeviceRetransmissions
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceRetransmissions = rowreq_ctx->data.clabWIFIAssociatedDeviceRetransmissions;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceRetransmissions_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceRetransmissions_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceRetransmissions_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceRetransmissions_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceRetransmissions_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceRetransmissions value.
     * set clabWIFIAssociatedDeviceRetransmissions value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceRetransmissions = clabWIFIAssociatedDeviceRetransmissions_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceRetransmissions_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceRetransmissions_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceRetransmissions_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceRetransmissions undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceRetransmissions data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceRetransmissions from rowreq_ctx->undo->clabWIFIAssociatedDeviceRetransmissions
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceRetransmissions = rowreq_ctx->undo->clabWIFIAssociatedDeviceRetransmissions;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceRetransmissions_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceActive
 * clabWIFIAssociatedDeviceActive is subid 8 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.8
 * Description:
This object is defined in TR-181 Device.WiFi.AssociatedDevice{i}.Active.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceActive_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceActive_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceActive_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceActive_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceActive value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceActive value not illegal */
} /* clabWIFIAssociatedDeviceActive_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceActive_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceActive_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceActive undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceActive data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceActive from rowreq_ctx->data.clabWIFIAssociatedDeviceActive
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceActive = rowreq_ctx->data.clabWIFIAssociatedDeviceActive;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceActive_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceActive_val
 *        A long containing the new value.
 */
int
clabWIFIAssociatedDeviceActive_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceActive_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceActive_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceActive value.
     * set clabWIFIAssociatedDeviceActive value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceActive = clabWIFIAssociatedDeviceActive_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceActive_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceActive_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceActive_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceActive undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceActive data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceActive from rowreq_ctx->undo->clabWIFIAssociatedDeviceActive
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceActive = rowreq_ctx->undo->clabWIFIAssociatedDeviceActive;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceActive_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceMaxPacketRetryCount
 * clabWIFIAssociatedDeviceMaxPacketRetryCount is subid 9 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.9
 * Description:
This object indicates the number of packets to be retransmitted
         to have an upper limit.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceMaxPacketRetryCount_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceMaxPacketRetryCount_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceMaxPacketRetryCount_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxPacketRetryCount_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceMaxPacketRetryCount value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceMaxPacketRetryCount value not illegal */
} /* clabWIFIAssociatedDeviceMaxPacketRetryCount_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceMaxPacketRetryCount_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxPacketRetryCount_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceMaxPacketRetryCount undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMaxPacketRetryCount data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxPacketRetryCount from rowreq_ctx->data.clabWIFIAssociatedDeviceMaxPacketRetryCount
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxPacketRetryCount = rowreq_ctx->data.clabWIFIAssociatedDeviceMaxPacketRetryCount;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxPacketRetryCount_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceMaxPacketRetryCount_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceMaxPacketRetryCount_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceMaxPacketRetryCount_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxPacketRetryCount_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceMaxPacketRetryCount value.
     * set clabWIFIAssociatedDeviceMaxPacketRetryCount value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceMaxPacketRetryCount = clabWIFIAssociatedDeviceMaxPacketRetryCount_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxPacketRetryCount_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceMaxPacketRetryCount_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxPacketRetryCount_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceMaxPacketRetryCount undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMaxPacketRetryCount data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceMaxPacketRetryCount from rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxPacketRetryCount
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceMaxPacketRetryCount = rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxPacketRetryCount;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxPacketRetryCount_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceStationCount
 * clabWIFIAssociatedDeviceStationCount is subid 10 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.10
 * Description:
This object indicates the total number of stations associated at
         any point in time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceStationCount_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_COUNTER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceStationCount_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceStationCount_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceStationCount_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceStationCount value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceStationCount value not illegal */
} /* clabWIFIAssociatedDeviceStationCount_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceStationCount_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceStationCount_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceStationCount undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceStationCount data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceStationCount from rowreq_ctx->data.clabWIFIAssociatedDeviceStationCount
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceStationCount = rowreq_ctx->data.clabWIFIAssociatedDeviceStationCount;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceStationCount_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceStationCount_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceStationCount_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceStationCount_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceStationCount_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceStationCount value.
     * set clabWIFIAssociatedDeviceStationCount value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceStationCount = clabWIFIAssociatedDeviceStationCount_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceStationCount_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceStationCount_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceStationCount_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceStationCount undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceStationCount data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceStationCount from rowreq_ctx->undo->clabWIFIAssociatedDeviceStationCount
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceStationCount = rowreq_ctx->undo->clabWIFIAssociatedDeviceStationCount;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceStationCount_undo */

/*---------------------------------------------------------------------
 * CLAB-WIFI-MIB::clabWIFIAssociatedDeviceEntry.clabWIFIAssociatedDeviceMaxNumOfStations
 * clabWIFIAssociatedDeviceMaxNumOfStations is subid 11 of clabWIFIAssociatedDeviceEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.4491.2.5.1.1.9.1.11
 * Description:
This object specifies the maximum number of STAs associated at
         any point in time.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param clabWIFIAssociatedDeviceMaxNumOfStations_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * clabWIFIAssociatedDeviceTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_UNSIGNED
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
clabWIFIAssociatedDeviceMaxNumOfStations_check_value( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceMaxNumOfStations_val)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxNumOfStations_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid clabWIFIAssociatedDeviceMaxNumOfStations value.
     */

    return MFD_SUCCESS; /* clabWIFIAssociatedDeviceMaxNumOfStations value not illegal */
} /* clabWIFIAssociatedDeviceMaxNumOfStations_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (clabWIFIAssociatedDeviceTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * clabWIFIAssociatedDeviceTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
clabWIFIAssociatedDeviceMaxNumOfStations_undo_setup( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxNumOfStations_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup clabWIFIAssociatedDeviceMaxNumOfStations undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMaxNumOfStations data
     * set rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxNumOfStations from rowreq_ctx->data.clabWIFIAssociatedDeviceMaxNumOfStations
     */
    rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxNumOfStations = rowreq_ctx->data.clabWIFIAssociatedDeviceMaxNumOfStations;


    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxNumOfStations_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param clabWIFIAssociatedDeviceMaxNumOfStations_val
 *        A u_long containing the new value.
 */
int
clabWIFIAssociatedDeviceMaxNumOfStations_set( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx, u_long clabWIFIAssociatedDeviceMaxNumOfStations_val )
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxNumOfStations_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set clabWIFIAssociatedDeviceMaxNumOfStations value.
     * set clabWIFIAssociatedDeviceMaxNumOfStations value in rowreq_ctx->data
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceMaxNumOfStations = clabWIFIAssociatedDeviceMaxNumOfStations_val;

    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxNumOfStations_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
clabWIFIAssociatedDeviceMaxNumOfStations_undo( clabWIFIAssociatedDeviceTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:clabWIFIAssociatedDeviceTable:clabWIFIAssociatedDeviceMaxNumOfStations_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up clabWIFIAssociatedDeviceMaxNumOfStations undo.
     */
    /*
     * copy clabWIFIAssociatedDeviceMaxNumOfStations data
     * set rowreq_ctx->data.clabWIFIAssociatedDeviceMaxNumOfStations from rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxNumOfStations
     */
    rowreq_ctx->data.clabWIFIAssociatedDeviceMaxNumOfStations = rowreq_ctx->undo->clabWIFIAssociatedDeviceMaxNumOfStations;

    
    return MFD_SUCCESS;
} /* clabWIFIAssociatedDeviceMaxNumOfStations_undo */

/** @} */
